#!/usr/bin/env bats
# Tests unitaires pour scripts/lib/prompt-builder.sh
# Fonctions testées : extract_frontmatter_value, extract_frontmatter_list,
#                     strip_frontmatter, agent_supports_target, get_agent_id,
#                     build_agent_content

setup() {
  TEST_DIR="$(mktemp -d)"

  # Sourcer dans l'ordre — common.sh recalcule HUB_DIR depuis BASH_SOURCE
  source "$BATS_TEST_DIRNAME/../scripts/common.sh"
  source "$BATS_TEST_DIRNAME/../scripts/lib/prompt-builder.sh"

  # Surcharger les variables après le source
  SKILLS_DIR="$TEST_DIR/skills"
  CANONICAL_AGENTS_DIR="$TEST_DIR/agents"

  # Mocker get_hub_version — pas de config/hub.json nécessaire
  get_hub_version() { echo "test"; }

  # Créer un agent minimal utilisé par les tests build_agent_content
  mkdir -p "$TEST_DIR/agents"
  mkdir -p "$TEST_DIR/skills/developer"

  cat > "$TEST_DIR/agents/test-agent.md" <<'AGENTEOF'
---
id: test-agent
label: TestAgent
description: Agent de test minimal
targets: [opencode, claude-code]
skills: [developer/test-skill]
---

# TestAgent

Corps de l'agent de test.
AGENTEOF

  cat > "$TEST_DIR/skills/developer/test-skill.md" <<'SKILLEOF'
---
name: test-skill
description: Skill de test minimal
---

# Skill de test

Contenu du skill de test.
SKILLEOF
}

teardown() {
  rm -rf "$TEST_DIR"
}

# ── extract_frontmatter_value ─────────────────────────────────────────────────

@test "extract_frontmatter_value : lit correctement le champ id" {
  run extract_frontmatter_value "$TEST_DIR/agents/test-agent.md" "id"
  [ "$status" -eq 0 ]
  [ "$output" = "test-agent" ]
}

@test "extract_frontmatter_value : lit correctement le champ label" {
  run extract_frontmatter_value "$TEST_DIR/agents/test-agent.md" "label"
  [ "$status" -eq 0 ]
  [ "$output" = "TestAgent" ]
}

# ── extract_frontmatter_list ──────────────────────────────────────────────────

@test "extract_frontmatter_list : parse une liste inline [a, b, c] en 3 lignes" {
  local tmp_file="$TEST_DIR/list-agent.md"
  cat > "$tmp_file" <<'EOF'
---
id: list-agent
skills: [developer/skill-a, developer/skill-b, developer/skill-c]
targets: [opencode]
---
EOF
  run extract_frontmatter_list "$tmp_file" "skills"
  [ "$status" -eq 0 ]
  [ "$(echo "$output" | wc -l | tr -d ' ')" -eq 3 ]
  echo "$output" | grep -q "developer/skill-a"
  echo "$output" | grep -q "developer/skill-b"
  echo "$output" | grep -q "developer/skill-c"
}

# ── strip_frontmatter ─────────────────────────────────────────────────────────

@test "strip_frontmatter : supprime le bloc frontmatter et retourne le corps" {
  run strip_frontmatter "$TEST_DIR/agents/test-agent.md"
  [ "$status" -eq 0 ]
  # Le corps doit être présent
  echo "$output" | grep -q "# TestAgent"
  # Le frontmatter ne doit pas être présent
  ! echo "$output" | grep -q "^id:"
  ! echo "$output" | grep -q "^---"
}

# ── agent_supports_target ─────────────────────────────────────────────────────

@test "agent_supports_target : retourne 0 pour une cible supportée (opencode)" {
  run agent_supports_target "$TEST_DIR/agents/test-agent.md" "opencode"
  [ "$status" -eq 0 ]
}

# ── get_agent_id ──────────────────────────────────────────────────────────────

@test "get_agent_id : retourne la valeur du champ id du frontmatter" {
  run get_agent_id "$TEST_DIR/agents/test-agent.md"
  [ "$status" -eq 0 ]
  [ "$output" = "test-agent" ]
}

# ── build_agent_content ───────────────────────────────────────────────────────

@test "build_agent_content : sans langue — pas d'instruction de langue dans l'output" {
  run build_agent_content "$TEST_DIR/agents/test-agent.md" "opencode"
  [ "$status" -eq 0 ]
  ! echo "$output" | grep -q "Langue de travail"
}

@test "build_agent_content : avec lang=english — instruction de langue présente" {
  run build_agent_content "$TEST_DIR/agents/test-agent.md" "opencode" "english"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "Langue de travail : english"
}

@test "build_agent_content : le header généré est présent" {
  run build_agent_content "$TEST_DIR/agents/test-agent.md" "opencode"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "<!-- generated by opencode-hub vtest"
}

@test "build_agent_content : agent inexistant — retourne exit non-zero" {
  run build_agent_content "$TEST_DIR/agents/inexistant.md" "opencode"
  [ "$status" -ne 0 ]
}

# ── build_dev_bootstrap_prompt ────────────────────────────────────────────────

@test "build_dev_bootstrap_prompt : JSON array valide — prompt avec tickets" {
  # Mocker bd pour retourner un JSON array valide
  bd() { echo '[{"id":"T-1","title":"Fix bug","status":"ready"}]'; }
  export -f bd
  run build_dev_bootstrap_prompt "$TEST_DIR"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "tickets délégués"
  echo "$output" | grep -q "T-1"
}

@test "build_dev_bootstrap_prompt : sortie non-JSON — fallback prompt sans tickets" {
  # Mocker bd pour retourner du texte d'erreur (pas un JSON array)
  bd() { echo "Error: database not found"; return 1; }
  export -f bd
  run build_dev_bootstrap_prompt "$TEST_DIR"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "Aucun ticket"
}

@test "build_dev_bootstrap_prompt : sortie vide — fallback prompt sans tickets" {
  # Mocker bd pour retourner une chaîne vide
  bd() { echo ""; }
  export -f bd
  run build_dev_bootstrap_prompt "$TEST_DIR"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "Aucun ticket"
}

# ── Intégrité skills ↔ agents ─────────────────────────────────────────────────

@test "intégrité : chaque skill référencé dans un agent existe sur le disque" {
  local hub_dir="$BATS_TEST_DIRNAME/.."
  local real_skills_dir="$hub_dir/skills"
  local real_agents_dir="$hub_dir/agents"
  local missing=""

  for agent_file in "$real_agents_dir"/*/*.md; do
    local agent_id
    agent_id=$(basename "$agent_file" .md)

    # Extraire la liste de skills du frontmatter
    local skills_line
    skills_line=$(awk '/^---$/{n++; next} n==1 && /^skills:/' "$agent_file")
    [ -z "$skills_line" ] && continue

    # Parser la liste [a, b, c]
    local skills_csv
    skills_csv=$(echo "$skills_line" | sed 's/^skills: *\[//;s/\] *$//')
    local IFS=','
    for skill in $skills_csv; do
      skill=$(echo "$skill" | sed 's/^ *//;s/ *$//')
      local skill_file="$real_skills_dir/${skill}.md"
      if [ ! -f "$skill_file" ]; then
        missing="${missing}  ${agent_id} → ${skill}\n"
      fi
    done
  done

  if [ -n "$missing" ]; then
    echo -e "Skills manquants :\n${missing}"
    return 1
  fi
}

# ── Cohérence data model dans les skills ──────────────────────────────────────

@test "data model : aucun skill n'utilise --priority high/medium/low (forme invalide)" {
  local hub_dir="$BATS_TEST_DIRNAME/.."
  local violations=""

  for skill_file in "$hub_dir"/skills/*/*.md; do
    if grep -n -- '--priority \(high\|medium\|low\)' "$skill_file" 2>/dev/null; then
      violations="${violations}  $(basename "$skill_file")\n"
    fi
  done

  if [ -n "$violations" ]; then
    echo -e "Skills utilisant --priority string (invalide) :\n${violations}"
    return 1
  fi
}

@test "data model : aucun skill n'utilise -t decision (type supprimé)" {
  local hub_dir="$BATS_TEST_DIRNAME/.."
  local violations=""

  for skill_file in "$hub_dir"/skills/*/*.md; do
    if grep -n -- '-t decision' "$skill_file" 2>/dev/null; then
      violations="${violations}  $(basename "$skill_file")\n"
    fi
  done

  if [ -n "$violations" ]; then
    echo -e "Skills utilisant -t decision (type supprimé) :\n${violations}"
    return 1
  fi
}

@test "data model : aucun skill, script ou agent n'utilise bd list --ready (utiliser bd ready)" {
  local hub_dir="$BATS_TEST_DIRNAME/.."
  local violations=""

  for f in "$hub_dir"/skills/*/*.md "$hub_dir"/scripts/*.sh "$hub_dir"/scripts/lib/*.sh "$hub_dir"/agents/*/*.md; do
    [ -f "$f" ] || continue
    if grep -n 'bd list --ready' "$f" 2>/dev/null; then
      violations="${violations}  $(basename "$f")\n"
    fi
  done

  if [ -n "$violations" ]; then
    echo -e "Fichiers utilisant bd list --ready (utiliser bd ready) :\n${violations}"
    return 1
  fi
}

@test "data model : aucun skill n'utilise -p 4 (priorité P4 supprimée)" {
  local hub_dir="$BATS_TEST_DIRNAME/.."
  local violations=""

  for skill_file in "$hub_dir"/skills/*/*.md; do
    if grep -n -- '-p 4' "$skill_file" 2>/dev/null; then
      violations="${violations}  $(basename "$skill_file")\n"
    fi
  done

  if [ -n "$violations" ]; then
    echo -e "Skills utilisant -p 4 (P4 supprimée) :\n${violations}"
    return 1
  fi
}

@test "data model : build_dev_bootstrap_prompt inclut l'étape review dans le workflow" {
  bd() { echo '[{"id":"T-1","title":"Test ticket","status":"ready"}]'; }
  export -f bd
  run build_dev_bootstrap_prompt "$TEST_DIR"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "review"
}

# ── build_review_bootstrap_prompt ─────────────────────────────────────────────

@test "build_review_bootstrap_prompt : contient la branche reviewée" {
  # Mocker git pour retourner un diff minimal
  git() {
    if [ "${3:-}" = "diff" ]; then
      echo "+ une ligne ajoutée"
      return 0
    fi
    command git "$@"
  }
  export -f git
  run build_review_bootstrap_prompt "$TEST_DIR" "TEST-PROJ" "feature/my-branch"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "feature/my-branch"
}

@test "build_review_bootstrap_prompt : contient le diff injecté" {
  git() {
    if [ "${3:-}" = "diff" ]; then
      echo "+ ligne ajoutée dans le diff"
      return 0
    fi
    command git "$@"
  }
  export -f git
  run build_review_bootstrap_prompt "$TEST_DIR" "TEST-PROJ" "feature/my-branch"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "ligne ajoutée dans le diff"
}

@test "build_review_bootstrap_prompt : contient les instructions de workflow" {
  git() {
    if [ "${3:-}" = "diff" ]; then
      echo "+ patch"
      return 0
    fi
    command git "$@"
  }
  export -f git
  run build_review_bootstrap_prompt "$TEST_DIR" "TEST-PROJ" "feature/my-branch"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "Workflow"
}

@test "build_review_bootstrap_prompt : contient le projet et le chemin" {
  git() {
    if [ "${3:-}" = "diff" ]; then
      echo "+ patch"
      return 0
    fi
    command git "$@"
  }
  export -f git
  run build_review_bootstrap_prompt "$TEST_DIR" "TEST-PROJ" "feature/my-branch"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "TEST-PROJ"
}

@test "build_review_bootstrap_prompt : mentionne CONVENTIONS.md si le fichier existe" {
  touch "$TEST_DIR/CONVENTIONS.md"
  git() {
    if [ "${3:-}" = "diff" ]; then
      echo "+ patch"
      return 0
    fi
    command git "$@"
  }
  export -f git
  run build_review_bootstrap_prompt "$TEST_DIR" "TEST-PROJ" "feature/my-branch"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "CONVENTIONS.md"
  rm -f "$TEST_DIR/CONVENTIONS.md"
}

@test "build_review_bootstrap_prompt : ne mentionne pas l'hint CONVENTIONS.md si absent" {
  git() {
    if [ "${3:-}" = "diff" ]; then
      echo "+ patch"
      return 0
    fi
    command git "$@"
  }
  export -f git
  run build_review_bootstrap_prompt "$TEST_DIR" "TEST-PROJ" "feature/my-branch"
  [ "$status" -eq 0 ]
  # L'hint contextuel "→ Lire CONVENTIONS.md" ne doit pas apparaître si le fichier est absent
  ! echo "$output" | grep -q "→ Lire CONVENTIONS.md"
}

@test "build_review_bootstrap_prompt : diff vide → message explicite" {
  git() {
    if [ "${3:-}" = "diff" ]; then
      echo ""
      return 0
    fi
    command git "$@"
  }
  export -f git
  run build_review_bootstrap_prompt "$TEST_DIR" "TEST-PROJ" "feature/my-branch"
  [ "$status" -eq 0 ]
  echo "$output" | grep -q "aucune différence"
}

# ── Intégrité des règles orchestrateur ────────────────────────────────────────

@test "orchestrator : bash, edit et write sont bien à deny dans le frontmatter" {
  local agent_file="$BATS_TEST_DIRNAME/../agents/planning/orchestrator.md"
  grep -q 'bash: deny' "$agent_file"
  grep -q 'edit: deny' "$agent_file"
  grep -q 'write: deny' "$agent_file"
}

@test "orchestrator : task deny par défaut avec allowlist explicite" {
  local agent_file="$BATS_TEST_DIRNAME/../agents/planning/orchestrator.md"
  grep -q '"*": deny' "$agent_file"
  grep -q '"planner": allow' "$agent_file"
  grep -q '"orchestrator-dev": allow' "$agent_file"
  grep -q '"debugger": allow' "$agent_file"
}

@test "orchestrator protocol : section 'Agent requis non disponible' présente" {
  local skill_file="$BATS_TEST_DIRNAME/../skills/orchestrator/orchestrator-protocol.md"
  grep -q 'Agent requis non disponible' "$skill_file"
}

@test "orchestrator protocol : table de substitution complète (7 auditor-*)" {
  local skill_file="$BATS_TEST_DIRNAME/../skills/orchestrator/orchestrator-protocol.md"
  grep -q 'auditor-security' "$skill_file"
  grep -q 'auditor-accessibility' "$skill_file"
  grep -q 'auditor-architecture' "$skill_file"
  grep -q 'auditor-performance' "$skill_file"
  grep -q 'auditor-privacy' "$skill_file"
  grep -q 'auditor-ecodesign' "$skill_file"
  grep -q 'auditor-observability' "$skill_file"
}

@test "orchestrator protocol : instruction de déploiement sans quitter OpenCode présente" {
  local skill_file="$BATS_TEST_DIRNAME/../skills/orchestrator/orchestrator-protocol.md"
  grep -q 'oc deploy opencode' "$skill_file"
}

@test "orchestrator protocol : Mode C conditionné à l'absence des fichiers de contexte" {
  local skill_file="$BATS_TEST_DIRNAME/../skills/orchestrator/orchestrator-protocol.md"
  grep -q 'ONBOARDING.md' "$skill_file"
  grep -q 'CONVENTIONS.md' "$skill_file"
}

@test "tool-question skill : règle de contexte pour les sous-agents présente" {
  local skill_file="$BATS_TEST_DIRNAME/../skills/posture/tool-question.md"
  grep -q 'sous-agent' "$skill_file"
  grep -q 'bloc de contexte' "$skill_file"
}

@test "orchestrator protocol : CP-0 sépare l'affichage du tableau et l'outil question" {
  local skill_file="$BATS_TEST_DIRNAME/../skills/orchestrator/orchestrator-protocol.md"
  grep -q 'Afficher dans le texte de la discussion' "$skill_file"
  grep -q 'Demander le mode via l.*outil.*question' "$skill_file"
}
