#!/bin/bash
# Generated by GitHub Copilot
# Adaptateur OpenCode — déploie vers .opencode/agents/ + config.json

source "$HUB_DIR/scripts/lib/prompt-builder.sh"

OPENCODE_MODEL="${OPENCODE_MODEL:-claude-sonnet-4-5}"

adapter_validate() {
  command -v opencode &>/dev/null || { log_error "OpenCode non installé → oc install"; return 1; }
}

adapter_needs_node() { return 0; }

adapter_deploy() {
  local deploy_dir="${1:-$HUB_DIR}"
  local out_dir="$deploy_dir/.opencode/agents"
  mkdir -p "$out_dir"
  [ -d "$CANONICAL_AGENTS_DIR" ] || { log_error "[opencode] Dossier agents/ introuvable"; return 1; }

  local deployed=0 agents_json=""

  for agent_file in "$CANONICAL_AGENTS_DIR"/*.md; do
    [ -f "$agent_file" ] || continue
    agent_supports_target "$agent_file" "opencode" || { log_warn "[opencode] Ignoré : $(basename "$agent_file")"; continue; }

    local agent_id; agent_id=$(get_agent_id "$agent_file")
    log_info "[opencode] Génération : $agent_id"
    build_agent_content "$agent_file" "opencode" > "$out_dir/${agent_id}.md"
    log_success "[opencode] $agent_id"

    [ -n "$agents_json" ] && agents_json+=","
    agents_json+="
    \"${agent_id}\": {
      \"model\": \"${OPENCODE_MODEL}\",
      \"system\": \".opencode/agents/${agent_id}.md\"
    }"
    deployed=$((deployed + 1))
  done

  mkdir -p "$deploy_dir/.opencode"
  cat > "$deploy_dir/.opencode/config.json" << JSEOF
{
  "model": "${OPENCODE_MODEL}",
  "agents": {${agents_json}
  }
}
JSEOF
  log_success "[opencode] config.json généré — $deployed agent(s)"
}

adapter_install() {
  if ! command -v opencode &>/dev/null; then
    command -v npm &>/dev/null || { log_error "[opencode] npm non disponible — relancez le terminal et réessayez"; return 1; }
    log_info "Installation de OpenCode..."
    npm install -g opencode-ai
    log_success "OpenCode installé"
  else
    log_success "OpenCode déjà installé ($(opencode --version 2>/dev/null || echo '?'))"
  fi
}

adapter_update() {
  command -v npm &>/dev/null || { log_error "[opencode] npm non disponible — relancez le terminal et réessayez"; return 1; }
  log_info "Mise à jour OpenCode..."
  npm update -g opencode-ai && log_success "OpenCode mis à jour" || log_warn "Échec mise à jour OpenCode"
}

adapter_start() {
  local project_path="$1" prompt="${2:-}"
  cd "$project_path"
  [ -n "$prompt" ] && exec opencode --prompt "$prompt" || exec opencode
}
