#!/bin/bash
# Generated by GitHub Copilot
# Adaptateur VS Code / Copilot
# Génère :
#   - .github/copilot-instructions.md  (instructions repo globales)
#   - .vscode/prompts/<agent>.prompt.md (prompts par rôle)

source "$HUB_DIR/scripts/lib/prompt-builder.sh"

adapter_validate() {
  # Le déploiement vscode ne nécessite pas le CLI 'code'.
  # Pour le lancement (adapter_start), la vérification est faite localement.
  # Ici on avertit si absent mais on laisse le déploiement continuer.
  command -v code &>/dev/null || log_warn "[vscode] CLI 'code' non détecté — déploiement possible, lancement impossible"
  return 0
}

adapter_needs_node() { return 1; }

adapter_deploy() {
  local deploy_dir="${1:-$HUB_DIR}"
  local github_dir="$deploy_dir/.github"
  local prompts_dir="$deploy_dir/.vscode/prompts"
  mkdir -p "$github_dir" "$prompts_dir"
  [ -d "$CANONICAL_AGENTS_DIR" ] || { log_error "[vscode] Dossier agents/ introuvable"; return 1; }

  # copilot-instructions.md depuis les skills universels
  log_info "[vscode] Génération copilot-instructions.md..."
  {
    echo "<!-- Généré par opencode-hub — ne pas éditer manuellement -->"
    echo "<!-- Régénérer : oc deploy vscode -->"
    echo ""
    for skill_name in "developer/dev-standards-universal" "developer/dev-standards-frontend-a11y"; do
      local sf="$SKILLS_DIR/${skill_name}.md"
      [ -f "$sf" ] && { get_skill_content "$sf"; echo ""; }
    done
  } > "$github_dir/copilot-instructions.md"
  log_success "[vscode] copilot-instructions.md"

  # Prompt par agent supportant vscode
  local deployed=0
  for agent_file in "$CANONICAL_AGENTS_DIR"/*.md; do
    [ -f "$agent_file" ] || continue
    agent_supports_target "$agent_file" "vscode" || { log_warn "[vscode] Ignoré : $(basename "$agent_file")"; continue; }

    local agent_id; agent_id=$(get_agent_id "$agent_file")
    local description; description=$(extract_frontmatter_value "$agent_file" "description")

    log_info "[vscode] Génération prompt : $agent_id"
    {
      echo "---"
      echo "mode: agent"
      [ -n "$description" ] && echo "description: '${description}'"
      echo "---"
      echo ""
      build_agent_content "$agent_file" "vscode"
    } > "$prompts_dir/${agent_id}.prompt.md"
    log_success "[vscode] ${agent_id}.prompt.md"
    deployed=$((deployed + 1))
  done

  echo ""
  log_success "[vscode] $deployed prompt(s) → .vscode/prompts/"
  log_info "→ Committer .github/copilot-instructions.md et .vscode/prompts/ dans le repo projet"
}

adapter_install() {
  command -v code &>/dev/null || { log_warn "VS Code non détecté → https://code.visualstudio.com"; return; }
  log_success "VS Code détecté"
  code --install-extension ms-vscode.copilot 2>/dev/null || true
  code --install-extension ms-vscode.copilot-chat 2>/dev/null || true
  log_success "Extensions Copilot installées"
}

adapter_update() {
  command -v code &>/dev/null || { log_warn "[vscode] Non détecté"; return; }
  code --install-extension ms-vscode.copilot 2>/dev/null || true
  code --install-extension ms-vscode.copilot-chat 2>/dev/null || true
  log_success "[vscode] Extensions mises à jour"
}

adapter_start() {
  local project_path="$1"
  command -v code &>/dev/null || { log_error "[vscode] CLI 'code' indisponible"; exit 1; }
  exec code "$project_path"
}
