#!/bin/bash
# Generated by GitHub Copilot
# Charge et expose les adaptateurs par cible (opencode, claude-code, vscode)

# Charge l'adaptateur d'une cible et expose ses fonctions
load_adapter() {
  local target="$1"
  local adapter_file="$ADAPTERS_DIR/${target}.adapter.sh"

  if [ ! -f "$adapter_file" ]; then
    log_error "Adaptateur inconnu : $target"
    log_info "Cibles disponibles : opencode, claude-code, vscode"
    exit 1
  fi

  source "$adapter_file"
}

# Retourne la cible par défaut depuis config/hub.json (ou 'opencode')
get_default_target() {
  if [ -f "$HUB_CONFIG" ] && command -v jq &>/dev/null; then
    jq -r '.default_target // "opencode"' "$HUB_CONFIG"
  else
    echo "opencode"
  fi
}

# Retourne les cibles actives depuis config/hub.json (ou 'opencode')
get_active_targets() {
  if [ -f "$HUB_CONFIG" ] && command -v jq &>/dev/null; then
    jq -r '.active_targets[]?' "$HUB_CONFIG"
  else
    echo "opencode"
  fi
}
