#!/bin/bash
# Assemble le contenu d'un agent canonique (agents/) avec ses skills injectés.
# Usage : source ce fichier, puis appeler build_agent_content <agent_file> [target]

# Guard contre le double sourcing
[[ -n "${_PROMPT_BUILDER_LOADED:-}" ]] && return 0
_PROMPT_BUILDER_LOADED=1

# Retourne la version du hub depuis config/hub.json
get_hub_version() {
  if command -v jq &>/dev/null && [ -f "$HUB_CONFIG" ]; then
    jq -r '.version // "unknown"' "$HUB_CONFIG" 2>/dev/null
  else
    grep '"version"' "$HUB_CONFIG" 2>/dev/null | head -1 \
      | sed 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' \
      || echo "unknown"
  fi
}

# Retourne le commentaire d'en-tête à insérer dans chaque fichier généré
build_generated_header() {
  local version; version=$(get_hub_version)
  echo "<!-- generated by opencode-hub v${version} — do not edit manually -->"
}

# Extrait la valeur d'une clé scalaire dans le frontmatter YAML
extract_frontmatter_value() {
  local file="$1" key="$2"
  sed -n '/^---$/,/^---$/p' "$file" | grep "^${key}:" | head -1 \
    | sed "s/^${key}:[[:space:]]*//"
}

# Extrait une liste inline [a, b, c] depuis le frontmatter
extract_frontmatter_list() {
  local file="$1" key="$2"
  extract_frontmatter_value "$file" "$key" \
    | tr -d '[]' | tr ',' '\n' \
    | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | grep -v '^$'
}

# Retourne le contenu d'un fichier Markdown en ignorant le bloc frontmatter YAML
strip_frontmatter() {
  local file="$1"
  if head -1 "$file" | grep -q '^---$'; then
    awk 'BEGIN{f=0;d=0} /^---$/{if(!f){f=1;next}else if(!d){d=1;next}} d{print}' "$file"
  else
    cat "$file"
  fi
}

# Vérifie si un agent supporte une cible donnée (via frontmatter targets)
agent_supports_target() {
  extract_frontmatter_list "$1" "targets" | grep -q "^${2}$"
}

# Retourne le mode de déploiement d'un agent (frontmatter mode:)
# Valeurs possibles : "primary" | "subagent" | "all"
# Fallback : "primary" si le champ est absent
get_agent_mode() {
  local mode
  mode=$(extract_frontmatter_value "$1" "mode")
  echo "${mode:-primary}"
}

# Retourne l'identifiant d'un agent (frontmatter id, ou nom de fichier sans extension)
get_agent_id() {
  local id
  id=$(extract_frontmatter_value "$1" "id")
  if [ -z "$id" ]; then
    basename "$1" .md
  else
    echo "$id"
  fi
}

# Construit le contenu final : corps de l'agent + skills injectés → stdout
# $2 (target) est réservé pour un futur filtrage par cible — non utilisé pour l'instant
# $3 (lang) optionnel — si non vide, injecte une instruction de langue en tête de l'agent
build_agent_content() {
  local agent_file="$1"
  # shellcheck disable=SC2034
  local target="${2:-opencode}"  # réservé : filtrage par cible (futur)
  local lang="${3:-}"
  [ -f "$agent_file" ] || { log_warn "Agent introuvable : $agent_file" >&2; return 1; }

  build_generated_header
  echo ""
  if [ -n "$lang" ]; then
    echo "> **Langue de travail : ${lang}.** Rédige toutes tes réponses, rapports et commentaires en ${lang}, quelle que soit la langue des instructions ci-dessous."
    echo ""
  fi
  strip_frontmatter "$agent_file"

  local skills=()
  while IFS= read -r skill; do
    skills+=("$skill")
  done < <(extract_frontmatter_list "$agent_file" "skills")

  if [ ${#skills[@]} -gt 0 ]; then
    echo ""
    echo "---"
    echo ""
    for skill in "${skills[@]}"; do
      [ -z "$skill" ] && continue
      local skill_file="$SKILLS_DIR/${skill}.md"
      if [ -f "$skill_file" ]; then
        strip_frontmatter "$skill_file"
        echo ""
      else
        log_warn "Skill introuvable : ${skill}.md" >&2
      fi
    done
  fi
}

# Construit le prompt de bootstrap pour le mode --dev (oc start --dev)
# Interroge bd ready dans le répertoire du projet
# @param $1 — project_path
# @param $2 — label (optionnel, défaut : "ai-delegated")
# @param $3 — assignee (optionnel, si fourni filtre par assignee au lieu du label)
build_dev_bootstrap_prompt() {
  local project_path="$1"
  local label="${2:-ai-delegated}"
  local assignee="${3:-}"
  local tickets

  if [ -n "$assignee" ]; then
    tickets=$(cd "$project_path" && bd ready --assignee "$assignee" --json 2>/dev/null) || tickets="[]"
  else
    tickets=$(cd "$project_path" && bd ready --label "$label" --json 2>/dev/null) || tickets="[]"
  fi
  # Valider que la sortie est un JSON array — si bd retourne du texte d'erreur, ignorer
  if [ -z "$tickets" ] || [[ "$tickets" != \[* ]]; then
    tickets="[]"
  fi

  local filter_desc
  if [ -n "$assignee" ]; then
    filter_desc="assigné à \"${assignee}\""
  else
    filter_desc="label \"${label}\""
  fi

  if [ "$tickets" = "[]" ] || [ "$tickets" = "null" ]; then
    cat <<EOF
Aucun ticket avec le ${filter_desc} n'est prêt à implémenter.

Pour déléguer un ticket à l'agent :
  bd label add <ID> ${label}

Pour voir tous les tickets ouverts :
  bd list -s open --json
EOF
  else
    cat <<EOF
Voici les tickets délégués à l'agent (${filter_desc}, statut ready) :

${tickets}

Workflow obligatoire :
1. bd show <ID>                  — lire le détail complet avant tout
2. bd update <ID> --claim        — clamer le ticket (atomique)
3. Implémenter + tester
4. bd update <ID> -s review      — passer en review
5. bd close <ID> --suggest-next  — clore après validation et passer au suivant

Commence par le ticket le plus prioritaire.
EOF
  fi
}

# Construit le prompt de bootstrap pour la commande oc audit
# @param $1 — project_path
# @param $2 — project_id (optionnel)
# @param $3 — audit_type (optionnel — vide = audit global)
build_audit_bootstrap_prompt() {
  local project_path="$1"
  local project_id="${2:-}"
  local audit_type="${3:-}"
  local scope_line=""
  [ -n "$audit_type" ] && scope_line="Périmètre : audit ${audit_type} uniquement."

  local project_info=""
  if [ -n "$project_id" ]; then
    project_info="Projet : ${project_id}
Chemin : ${project_path}"
  else
    project_info="Chemin : ${project_path}"
  fi

  cat <<EOF
Effectue un audit du projet.

${project_info}
${scope_line:+
${scope_line}}
PHASE 1 — Contexte projet (OBLIGATOIRE avant toute délégation aux sous-agents)

Si le fichier ONBOARDING.md existe à la racine du projet :
  → Le lire en priorité — il contient déjà la stack, la structure et les points d'attention
  → Annoncer : "Contexte projet chargé depuis ONBOARDING.md" suivi d'un résumé en 1-2 phrases

Sinon, reconnaissance rapide (3-4 fichiers uniquement) :
  → Lire le fichier de dépendances racine (package.json, composer.json, requirements.txt…)
  → Inspecter la structure des répertoires principaux (src/, app/, etc.)
  → Identifier 1-2 fichiers de config pertinents selon le type d'audit (.env.example, nginx.conf…)
  → Résumer en 5 lignes : stack, répertoires principaux, points d'attention immédiats visibles

PHASE 2 — Délégation aux sous-agents

Déléguer aux sous-agents appropriés en leur passant le résumé du contexte (Phase 1) en préambule.
Chaque sous-agent travaille en lecture seule et produit un rapport structuré.
EOF
}

# Construit le prompt de bootstrap pour le mode --onboard (oc start --onboard)
# Déclenche l'agent onboarder en lecture seule sur le projet
# @param $1 — project_path
# @param $2 — project_id (optionnel)
# @param $3 — hub_dir (optionnel — défaut : $HUB_DIR)
build_onboard_bootstrap_prompt() {
  local project_path="$1"
  local project_id="${2:-}"
  local hub_dir="${3:-${HUB_DIR:-}}"
  local projects_file="${hub_dir:+${hub_dir}/projects/projects.md}"

  local project_info=""
  if [ -n "$project_id" ]; then
    project_info="Projet : ${project_id}
Chemin : ${project_path}"
  else
    project_info="Chemin : ${project_path}"
  fi

  local hub_info=""
  if [ -n "$hub_dir" ] && [ -n "$projects_file" ]; then
    hub_info="
Hub : ${hub_dir}
projects.md : ${projects_file}"
  fi

  cat <<EOF
Effectue une exploration complète du projet pour produire un rapport de contexte.

${project_info}${hub_info}

Workflow :
1. Annoncer ce qui va être exploré
2. ÉTAPE 1 — Détecter la stack (racine du projet)
3. ÉTAPE 2 — Explorer adaptativement selon le profil détecté
4. ÉTAPE 3 — Lire les tickets Beads (bd list -s open) + ADRs si disponibles
5. ÉTAPE 4 — Produire le rapport de contexte structuré
6. ÉTAPE 5 — Écrire ONBOARDING.md à la racine du projet
7. ÉTAPE 6 — Détecter les conventions et écrire CONVENTIONS.md à la racine du projet

Règles :
- Lecture seule — tu ne modifies aucun fichier du projet (sauf ONBOARDING.md, CONVENTIONS.md et .gitignore)
- Rapport honnête : signaler les points critiques (🔴), importants (🟠), améliorations (🟡)
- Lister les zones d'ombre non résolues
- Après le rapport complet dans la conversation, écrire ONBOARDING.md à la racine du projet
  (sans les sections Agents recommandés et Commandes utiles)
- Ensuite, détecter et écrire CONVENTIONS.md à la racine du projet
  (linting config, tsconfig, package.json, git log, fichiers représentatifs de la codebase)
- Ajouter ONBOARDING.md et CONVENTIONS.md au .gitignore du projet
  (créer le fichier .gitignore s'il n'existe pas)
- Si le champ Stack est absent ou incomplet dans projects.md, le mettre à jour
  (chemin fourni ci-dessus — demander confirmation explicite avant toute écriture)
EOF
}

# Construit le prompt de bootstrap pour la commande oc conventions
# Déclenche la détection ciblée des conventions du projet → CONVENTIONS.md
# @param $1 — project_path
# @param $2 — project_id (optionnel)
# @param $3 — hub_dir (optionnel)
build_conventions_bootstrap_prompt() {
  local project_path="$1"
  local project_id="${2:-}"
  local hub_dir="${3:-${HUB_DIR:-}}"
  local projects_file="${hub_dir:+${hub_dir}/projects/projects.md}"

  local project_info=""
  if [ -n "$project_id" ]; then
    project_info="Projet : ${project_id}
Chemin : ${project_path}"
  else
    project_info="Chemin : ${project_path}"
  fi

  local hub_info=""
  if [ -n "$hub_dir" ] && [ -n "$projects_file" ]; then
    hub_info="
Hub : ${hub_dir}
projects.md : ${projects_file}"
  fi

  cat <<EOF
Détecte et documente les conventions de développement de ce projet dans CONVENTIONS.md.

${project_info}${hub_info}

Workflow :
1. Annoncer ce qui va être lu
2. ÉTAPE 1 — Lire les configs linting/formatting
   (.eslintrc*, eslint.config.*, .prettierrc*, .editorconfig, biome.json, ruff.toml, etc.)
3. ÉTAPE 2 — Lire la config langage et typage
   (tsconfig.json, pyproject.toml, go.mod, etc.)
4. ÉTAPE 3 — Lire les dépendances et libs choisies
   (package.json, pyproject.toml, Gemfile, etc.)
5. ÉTAPE 4 — Lire les conventions Git
   (.commitlintrc*, .husky/, CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md)
   + git log --oneline -20 pour observer les conventions réelles
6. ÉTAPE 5 — Inférer le nommage depuis 5 à 10 fichiers représentatifs de la codebase
   (composants, services, tests, stores — selon le profil du projet)
7. ÉTAPE 6 — Lire les configs de test
   (vitest.config.*, jest.config.*, pytest.ini, playwright.config.*, etc.)
8. ÉTAPE 7 — Écrire CONVENTIONS.md à la racine du projet
   ⚠️ Si CONVENTIONS.md existe déjà → afficher la date du fichier existant et demander confirmation
   avant d'écraser ("Écraser / Conserver l'existant")
   Ajouter CONVENTIONS.md au .gitignore s'il n'y est pas déjà

Règles :
- Baser chaque convention sur un fichier réellement lu — ne jamais inventer
- Signaler les incohérences détectées (ex: config lint ≠ pratique observée dans le code)
- Section "Zones d'ombre" pour ce qui n'a pas pu être déterminé
- Ne pas modifier d'autres fichiers du projet
EOF
}
