#!/bin/bash
# Assemble le contenu d'un agent canonique (agents/) avec ses skills injectés.
# Usage : source ce fichier, puis appeler build_agent_content <agent_file> [target]

# Guard contre le double sourcing
[[ -n "${_PROMPT_BUILDER_LOADED:-}" ]] && return 0
_PROMPT_BUILDER_LOADED=1

# Retourne la version du hub depuis config/hub.json
get_hub_version() {
  if command -v jq &>/dev/null && [ -f "$HUB_CONFIG" ]; then
    jq -r '.version // "unknown"' "$HUB_CONFIG" 2>/dev/null
  else
    grep '"version"' "$HUB_CONFIG" 2>/dev/null | head -1 \
      | sed 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' \
      || echo "unknown"
  fi
}

# Retourne le commentaire d'en-tête à insérer dans chaque fichier généré
build_generated_header() {
  local version; version=$(get_hub_version)
  echo "<!-- generated by opencode-hub v${version} — do not edit manually -->"
}

# Extrait la valeur d'une clé scalaire dans le frontmatter YAML
extract_frontmatter_value() {
  local file="$1" key="$2"
  sed -n '/^---$/,/^---$/p' "$file" | grep "^${key}:" | head -1 \
    | sed "s/^${key}:[[:space:]]*//"
}

# Extrait une liste inline [a, b, c] depuis le frontmatter
extract_frontmatter_list() {
  local file="$1" key="$2"
  extract_frontmatter_value "$file" "$key" \
    | tr -d '[]' | tr ',' '\n' \
    | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | grep -v '^$'
}

# Retourne le contenu d'un fichier Markdown en ignorant le bloc frontmatter YAML
strip_frontmatter() {
  local file="$1"
  if head -1 "$file" | grep -q '^---$'; then
    awk 'BEGIN{f=0;d=0} /^---$/{if(!f){f=1;next}else if(!d){d=1;next}} d{print}' "$file"
  else
    cat "$file"
  fi
}

# Vérifie si un agent supporte une cible donnée (via frontmatter targets)
agent_supports_target() {
  extract_frontmatter_list "$1" "targets" | grep -q "^${2}$"
}

# Retourne l'identifiant d'un agent (frontmatter id, ou nom de fichier sans extension)
get_agent_id() {
  local id
  id=$(extract_frontmatter_value "$1" "id")
  if [ -z "$id" ]; then
    basename "$1" .md
  else
    echo "$id"
  fi
}

# Construit le contenu final : corps de l'agent + skills injectés → stdout
# $2 (target) est réservé pour un futur filtrage par cible — non utilisé pour l'instant
# $3 (lang) optionnel — si non vide, injecte une instruction de langue en tête de l'agent
build_agent_content() {
  local agent_file="$1"
  # shellcheck disable=SC2034
  local target="${2:-opencode}"  # réservé : filtrage par cible (futur)
  local lang="${3:-}"
  [ -f "$agent_file" ] || { log_warn "Agent introuvable : $agent_file" >&2; return 1; }

  build_generated_header
  echo ""
  if [ -n "$lang" ]; then
    echo "> **Langue de travail : ${lang}.** Rédige toutes tes réponses, rapports et commentaires en ${lang}, quelle que soit la langue des instructions ci-dessous."
    echo ""
  fi
  strip_frontmatter "$agent_file"

  local skills=()
  while IFS= read -r skill; do
    skills+=("$skill")
  done < <(extract_frontmatter_list "$agent_file" "skills")

  if [ ${#skills[@]} -gt 0 ]; then
    echo ""
    echo "---"
    echo ""
    for skill in "${skills[@]}"; do
      [ -z "$skill" ] && continue
      local skill_file="$SKILLS_DIR/${skill}.md"
      if [ -f "$skill_file" ]; then
        strip_frontmatter "$skill_file"
        echo ""
      else
        log_warn "Skill introuvable : ${skill}.md" >&2
      fi
    done
  fi
}

# Construit le prompt de bootstrap pour le mode --dev (oc start --dev)
# Interroge bd ready --label ai-delegated dans le répertoire du projet
# et retourne un prompt contextuel prêt à être injecté dans l'outil IA
build_dev_bootstrap_prompt() {
  local project_path="$1"
  local tickets

  tickets=$(cd "$project_path" && bd ready --label ai-delegated --json 2>/dev/null) || tickets="[]"
  # Valider que la sortie est un JSON array — si bd retourne du texte d'erreur, ignorer
  if [ -z "$tickets" ] || [[ "$tickets" != \[* ]]; then
    tickets="[]"
  fi

  if [ "$tickets" = "[]" ] || [ "$tickets" = "null" ]; then
    cat <<'EOF'
Tu es le Developer. Aucun ticket avec le label "ai-delegated" n'est prêt à implémenter.

Pour déléguer un ticket à l'agent :
  bd label add <ID> ai-delegated

Pour voir tous les tickets ouverts :
  bd list -s open --json
EOF
  else
    cat <<EOF
Tu es le Developer. Voici les tickets délégués à l'agent (label "ai-delegated", statut ready) :

${tickets}

Workflow obligatoire :
1. bd show <ID>                  — lire le détail complet avant tout
2. bd update <ID> --claim        — clamer le ticket (atomique)
3. Implémenter + tester
4. bd update <ID> -s review      — passer en review
5. bd close <ID> --suggest-next  — clore après validation et passer au suivant

Commence par le ticket le plus prioritaire.
EOF
  fi
}
