#!/bin/bash
# Generated by GitHub Copilot
# Assemble le contenu d'un agent canonique (agents/) avec ses skills injectés.
# Usage : source ce fichier, puis appeler build_agent_content <agent_file> [target]

# Extrait la valeur d'une clé scalaire dans le frontmatter YAML
extract_frontmatter_value() {
  local file="$1" key="$2"
  sed -n '/^---$/,/^---$/p' "$file" | grep "^${key}:" | head -1 \
    | sed "s/^${key}:[[:space:]]*//"
}

# Extrait une liste inline [a, b, c] depuis le frontmatter
extract_frontmatter_list() {
  local file="$1" key="$2"
  extract_frontmatter_value "$file" "$key" \
    | tr -d '[]' | tr ',' '\n' \
    | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | grep -v '^$'
}

# Retourne le corps d'un fichier Markdown en ignorant le bloc frontmatter
get_agent_body() {
  local file="$1"
  if head -1 "$file" | grep -q '^---$'; then
    awk 'BEGIN{f=0;d=0} /^---$/{if(!f){f=1;next}else if(!d){d=1;next}} d{print}' "$file"
  else
    cat "$file"
  fi
}

# Retourne le contenu d'un skill en ignorant son frontmatter
get_skill_content() {
  local file="$1"
  if head -1 "$file" | grep -q '^---$'; then
    awk 'BEGIN{f=0;d=0} /^---$/{if(!f){f=1;next}else if(!d){d=1;next}} d{print}' "$file"
  else
    cat "$file"
  fi
}

# Vérifie si un agent supporte une cible donnée (via frontmatter targets)
agent_supports_target() {
  extract_frontmatter_list "$1" "targets" | grep -q "^${2}$"
}

# Retourne l'identifiant d'un agent (frontmatter id, ou nom de fichier sans extension)
get_agent_id() {
  local id
  id=$(extract_frontmatter_value "$1" "id")
  [ -z "$id" ] && basename "$1" .md || echo "$id"
}

# Construit le contenu final : corps de l'agent + skills injectés → stdout
build_agent_content() {
  local agent_file="$1" target="${2:-opencode}"
  [ -f "$agent_file" ] || { log_warn "Agent introuvable : $agent_file" >&2; return 1; }

  get_agent_body "$agent_file"

  local skills=()
  mapfile -t skills < <(extract_frontmatter_list "$agent_file" "skills")

  if [ ${#skills[@]} -gt 0 ]; then
    echo ""
    echo "---"
    echo ""
    for skill in "${skills[@]}"; do
      [ -z "$skill" ] && continue
      local skill_file="$SKILLS_DIR/${skill}.md"
      if [ -f "$skill_file" ]; then
        get_skill_content "$skill_file"
        echo ""
      else
        log_warn "Skill introuvable : ${skill}.md" >&2
      fi
    done
  fi
}
