#!/bin/bash
# Generated by GitHub Copilot
# Gestion des skills externes (context7, etc.)
# Usage : ./oc.sh skills <commande> [args]

source "$(cd "$(dirname "$0")" && pwd)/common.sh"

EXTERNAL_SKILLS_DIR="$HUB_DIR/skills/external"
SOURCES_FILE="$EXTERNAL_SKILLS_DIR/.sources.json"
# Dossier d'installation universelle ctx7 — utilisé comme relais avant copie locale
UNIVERSAL_SKILLS_DIR="$HOME/.agents/skills"

# ── HELPERS ──────────────────────────────────────────────────────────────────

# Vérifie que npx est disponible (requis pour ctx7)
_require_npx() {
  if ! command -v npx &>/dev/null; then
    log_error "npx n'est pas disponible. Installez Node.js → https://nodejs.org"
    exit 1
  fi
}

# Initialise le dossier external et le fichier de sources s'ils n'existent pas
_init_external() {
  mkdir -p "$EXTERNAL_SKILLS_DIR"
  if [ ! -f "$SOURCES_FILE" ]; then
    echo '{}' > "$SOURCES_FILE"
  fi
}

# Enregistre la provenance d'un skill dans .sources.json
_record_source() {
  local skill_name="$1" repo="$2" downloaded_at="$3"
  if ! command -v jq &>/dev/null; then
    log_warn "jq non disponible — provenance non enregistrée."
    return
  fi
  local tmp
  tmp=$(mktemp)
  jq --arg name "$skill_name" \
     --arg repo "$repo" \
     --arg date "$downloaded_at" \
     '.[$name] = {repo: $repo, downloaded_at: $date}' \
     "$SOURCES_FILE" > "$tmp" && mv "$tmp" "$SOURCES_FILE"
}

# Supprime la provenance d'un skill de .sources.json
_remove_source() {
  local skill_name="$1"
  if ! command -v jq &>/dev/null; then
    return
  fi
  local tmp
  tmp=$(mktemp)
  jq --arg name "$skill_name" 'del(.[$name])' "$SOURCES_FILE" > "$tmp" && mv "$tmp" "$SOURCES_FILE"
}

# ── SEARCH ───────────────────────────────────────────────────────────────────

##
# Recherche des skills sur context7 par mot-clé.
# @param {string} $1 — Terme de recherche
##
cmd_search() {
  local query="${1:-}"
  if [ -z "$query" ]; then
    log_error "Usage : oc skills search <query>"
    log_info  "Exemple : oc skills search pdf"
    exit 1
  fi
  _require_npx
  log_title "Recherche de skills : \"$query\""
  echo ""
  # On autorise un code de retour non-nul (ex: aucun résultat) sans interrompre le script
  npx ctx7 skills search "$query" || true
}

# ── INFO ─────────────────────────────────────────────────────────────────────

##
# Prévisualise les skills disponibles dans un dépôt context7 sans les installer.
# @param {string} $1 — Identifiant du dépôt au format /owner/repo
##
cmd_info() {
  local repo="${1:-}"
  if [ -z "$repo" ]; then
    log_error "Usage : oc skills info /owner/repo"
    log_info  "Exemple : oc skills info /anthropics/skills"
    exit 1
  fi
  _require_npx
  log_title "Skills disponibles dans $repo"
  echo ""
  npx ctx7 skills info "$repo" || true
}

# ── ADD ──────────────────────────────────────────────────────────────────────

##
# Télécharge un skill depuis context7 et l'ajoute dans skills/external/.
# Utilise ctx7 CLI comme relais : install dans ~/.agents/skills/ puis copie locale.
# @param {string} $1 — Identifiant du dépôt au format /owner/repo
# @param {string} $2 — (optionnel) Nom du skill à installer
##
cmd_add() {
  local repo="${1:-}" skill_name="${2:-}"
  if [ -z "$repo" ]; then
    log_error "Usage : oc skills add /owner/repo [skill-name]"
    log_info  "Exemple : oc skills add /anthropics/skills pdf"
    log_info  "Pour voir les skills disponibles : oc skills info /owner/repo"
    exit 1
  fi
  _require_npx
  _init_external

  log_title "Ajout d'un skill externe"

  # Si aucun nom fourni, afficher la liste et demander
  if [ -z "$skill_name" ]; then
    log_info "Skills disponibles dans $repo :"
    echo ""
    npx ctx7 skills info "$repo" 2>/dev/null || true
    echo ""
    read -rp "Nom du skill à installer : " skill_name
    if [ -z "$skill_name" ]; then
      log_error "Nom de skill requis. Annulé."
      exit 1
    fi
  fi

  local dest="$EXTERNAL_SKILLS_DIR/${skill_name}.md"

  # Confirmation si le skill existe déjà localement
  if [ -f "$dest" ]; then
    log_warn "Le skill 'external/${skill_name}' existe déjà."
    read -rp "Écraser ? (y/N) : " confirm
    [[ "$confirm" =~ ^[Yy]$ ]] || { log_info "Annulé."; exit 0; }
  fi

  log_info "Téléchargement de '$skill_name' depuis $repo via ctx7..."
  mkdir -p "$UNIVERSAL_SKILLS_DIR"

  # Le chemin attendu après installation ctx7 --universal
  local installed_file="$UNIVERSAL_SKILLS_DIR/${skill_name}.md"

  # Si déjà présent dans le cache universel, on réutilise (ctx7 peut échouer sinon)
  if [ ! -f "$installed_file" ]; then
    npx ctx7 skills install "$repo" "$skill_name" --universal

    # Fallback : recherche par nom partiel si le fichier n'a pas l'extension .md attendue
    if [ ! -f "$installed_file" ]; then
      installed_file=$(find "$UNIVERSAL_SKILLS_DIR" -iname "${skill_name}.*" -type f 2>/dev/null | head -1)
    fi
  fi

  if [ -z "$installed_file" ] || [ ! -f "$installed_file" ]; then
    log_error "Skill installé mais introuvable dans $UNIVERSAL_SKILLS_DIR"
    log_warn  "Vérifiez manuellement le contenu de ce dossier."
    exit 1
  fi

  # Copie vers skills/external/ — seule cette copie est utilisée par le hub
  cp "$installed_file" "$dest"

  # Enregistrement de la provenance
  local now
  now=$(date +%Y-%m-%d)
  _record_source "$skill_name" "$repo" "$now"

  log_success "Skill '$skill_name' ajouté → skills/external/${skill_name}.md"
  echo ""
  log_info "Pour l'utiliser dans un agent, ajoutez 'external/${skill_name}' à la liste"
  log_info "  skills: de son fichier agents/*.md, puis relancez : ./oc.sh deploy all"
}

# ── LIST ─────────────────────────────────────────────────────────────────────

##
# Liste tous les skills disponibles : locaux (skills/) et externes (skills/external/).
##
cmd_list() {
  log_title "Skills disponibles"
  echo ""

  echo -e "${BOLD}Skills locaux :${RESET}"
  local found_local=0
  while IFS= read -r f; do
    echo "  ${f#$HUB_DIR/skills/}" | sed 's/\.md$//'
    found_local=1
  done < <(find "$HUB_DIR/skills" -name "*.md" -not -path "*/external/*" -type f 2>/dev/null | sort)
  [ "$found_local" -eq 0 ] && echo "  (aucun)"

  echo ""
  echo -e "${BOLD}Skills externes (context7) :${RESET}"
  local found_ext=0
  for f in "$EXTERNAL_SKILLS_DIR"/*.md; do
    [ -f "$f" ] || continue
    local name
    name=$(basename "$f" .md)
    local repo=""
    if [ -f "$SOURCES_FILE" ] && command -v jq &>/dev/null; then
      repo=$(jq -r --arg n "$name" '.[$n].repo // ""' "$SOURCES_FILE")
    fi
    if [ -n "$repo" ]; then
      echo "  external/$name  ← $repo"
    else
      echo "  external/$name"
    fi
    found_ext=1
  done
  [ "$found_ext" -eq 0 ] && echo "  (aucun — utilisez : oc skills add /owner/repo [name])"

  echo ""
}

# ── SYNC ─────────────────────────────────────────────────────────────────────

##
# Re-télécharge tous les skills externes enregistrés dans .sources.json.
# Utile après un git clone (skills/external/ est gitignorés).
##
cmd_sync() {
  _require_npx
  _init_external

  if ! command -v jq &>/dev/null; then
    log_error "jq est requis pour lire les sources enregistrées."
    exit 1
  fi

  if [ ! -f "$SOURCES_FILE" ] || [ "$(cat "$SOURCES_FILE")" = '{}' ]; then
    log_info "Aucun skill externe enregistré. Rien à synchroniser."
    return
  fi

  log_title "Synchronisation des skills externes"
  echo ""

  local count=0
  while IFS= read -r skill_name; do
    [ -z "$skill_name" ] && continue
    local repo
    repo=$(jq -r --arg n "$skill_name" '.[$n].repo' "$SOURCES_FILE")
    log_info "Re-téléchargement : $skill_name depuis $repo..."
    # Forcer le re-téléchargement en supprimant le cache universel
    rm -f "$UNIVERSAL_SKILLS_DIR/${skill_name}.md"
    cmd_add "$repo" "$skill_name"
    count=$((count + 1))
  done < <(jq -r 'keys[]' "$SOURCES_FILE")

  echo ""
  log_success "$count skill(s) synchronisé(s)."
}

# ── REMOVE ───────────────────────────────────────────────────────────────────

##
# Supprime un skill externe du hub (ne supprime pas le cache ~/.agents/skills/).
# @param {string} $1 — Nom du skill à supprimer (sans préfixe external/)
##
cmd_remove() {
  local skill_name="${1:-}"
  if [ -z "$skill_name" ]; then
    log_error "Usage : oc skills remove <skill-name>"
    log_info  "Exemple : oc skills remove pdf"
    log_info  "Utilisez 'oc skills list' pour voir les skills disponibles."
    exit 1
  fi

  # Accepter "external/pdf" ou "pdf"
  skill_name="${skill_name#external/}"

  local dest="$EXTERNAL_SKILLS_DIR/${skill_name}.md"
  if [ ! -f "$dest" ]; then
    log_error "Skill externe '${skill_name}' introuvable."
    log_info  "Utilisez 'oc skills list' pour voir les skills disponibles."
    exit 1
  fi

  read -rp "Supprimer le skill externe '${skill_name}' ? (y/N) : " confirm
  [[ "$confirm" =~ ^[Yy]$ ]] || { log_info "Annulé."; exit 0; }

  rm "$dest"
  [ -f "$SOURCES_FILE" ] && _remove_source "$skill_name"

  log_success "Skill '${skill_name}' supprimé."
  log_info    "N'oubliez pas de le retirer de la liste skills: de vos agents si nécessaire."
}

# ── DISPATCH ─────────────────────────────────────────────────────────────────

SUBCOMMAND="${1:-}"
shift 2>/dev/null || true

case "$SUBCOMMAND" in
  search) cmd_search "$@" ;;
  info)   cmd_info "$@" ;;
  add)    cmd_add "$@" ;;
  list)   cmd_list ;;
  sync)   cmd_sync ;;
  remove) cmd_remove "$@" ;;
  *)
    echo -e "${BOLD}oc skills — Gestion des skills externes${RESET}"
    echo ""
    echo "  search <query>             Rechercher des skills sur context7"
    echo "  info /owner/repo           Prévisualiser les skills d'un dépôt"
    echo "  add /owner/repo [name]     Ajouter un skill externe"
    echo "  list                       Lister tous les skills (locaux + externes)"
    echo "  sync                       Re-télécharger les skills externes enregistrés"
    echo "  remove <name>              Supprimer un skill externe"
    echo ""
    echo -e "${BOLD}Exemples :${RESET}"
    echo "  ./oc.sh skills search pdf"
    echo "  ./oc.sh skills info /anthropics/skills"
    echo "  ./oc.sh skills add /anthropics/skills pdf"
    echo "  ./oc.sh skills list"
    echo ""
    ;;
esac
