#!/bin/bash
set -euo pipefail
source "$(cd "$(dirname "$0")" && pwd)/common.sh"

resolve_oc_lang

echo -e "${BOLD}opencode-hub — oc.sh${RESET}"
echo ""
echo -e "${BOLD}$(t help.usage)${RESET}"
echo "  ./oc.sh <commande> [arguments]"
echo ""
echo -e "${BOLD}$(t help.section.setup)${RESET}"
echo "  $(t help.install)"
echo "  $(t help.uninstall)"
echo "  $(t help.init)"
echo "  $(t help.version)"
echo ""
echo -e "${BOLD}$(t help.section.projects)${RESET}"
echo "  $(t help.list)"
echo "  $(t help.status)"
echo "  $(t help.remove)"
echo "  $(t help.remove_clean)"
echo ""
echo -e "${BOLD}$(t help.section.launch)${RESET}"
echo "  $(t help.start)"
echo "  $(t help.start_dev)"
echo "  $(t help.start_dev_label)"
echo "  $(t help.start_dev_assignee)"
echo "  $(t help.start_onboard)"
echo ""
echo -e "${BOLD}$(t help.section.analysis)${RESET}"
echo "  $(t help.audit)"
echo "  $(t help.audit_type)"
echo "  $(t help.audit_types)"
echo "  $(t help.audit_types2)"
echo "  $(t help.review)"
echo "  $(t help.review_branch)"
echo "  $(t help.conventions)"
echo "  $(t help.conventions_force)"
echo ""
echo -e "${BOLD}$(t help.section.maintenance)${RESET}"
echo "  $(t help.deploy)"
echo "  $(t help.deploy_check)"
echo "  $(t help.deploy_diff)"
echo "  $(t help.sync)"
echo "  $(t help.sync_dryrun)"
  echo "  $(t help.update)"
  echo "  $(t help.upgrade)"
echo ""
echo -e "${BOLD}$(t help.section.config)${RESET}"
echo "  $(t help.config_set)"
echo "  $(t help.config_set_desc)"
echo "  $(t help.config_get)"
echo "  $(t help.config_list)"
echo "  $(t help.config_unset)"
echo "  $(t help.config_language)"
echo "  $(t help.provider_list)"
echo "  $(t help.provider_set_default)"
echo "  $(t help.provider_set)"
echo "  $(t help.provider_get)"
echo "  $(t help.target_info)"
echo "  $(t help.target_select)"
echo ""
echo -e "${BOLD}$(t help.section.deploy_targets)${RESET}"
echo "  $(t help.deploy_target.opencode)"
echo "  $(t help.deploy_target.claude)"
echo "  $(t help.deploy_target.all)"
echo ""
echo -e "${BOLD}$(t help.section.agents)${RESET}"
echo "  $(t help.agent_list)"
echo "  $(t help.agent_create)"
echo "  $(t help.agent_edit)"
echo "  $(t help.agent_info)"
echo "  $(t help.agent_select)"
echo "  $(t help.agent_mode)"
echo "  $(t help.agent_validate)"
echo "  $(t help.agent_keytest)"
echo ""
echo -e "${BOLD}$(t help.section.skills)${RESET}"
echo "  $(t help.skills_search)"
echo "  $(t help.skills_info)"
echo "  $(t help.skills_add)"
echo "  $(t help.skills_list)"
echo "  $(t help.skills_update)"
echo "  $(t help.skills_used_by)"
echo "  $(t help.skills_sync)"
echo "  $(t help.skills_remove)"
echo ""
echo -e "${BOLD}$(t help.section.beads)${RESET}"
echo "  $(t help.beads_status)"
echo "  $(t help.beads_init)"
echo "  $(t help.beads_list)"
echo "  $(t help.beads_create)"
echo "  $(t help.beads_create_desc)"
echo "  $(t help.beads_open)"
echo "  $(t help.beads_sync)"
echo "  $(t help.beads_sync_desc)"
echo "  $(t help.beads_tracker_status)"
echo "  $(t help.beads_tracker_setup)"
echo "  $(t help.beads_tracker_switch)"
echo ""
echo -e "${BOLD}$(t help.section.examples)${RESET}"
echo "  ./oc.sh skills search pdf"
echo "  ./oc.sh skills add /owner/repo skill-name"
echo "  Puis dans agents/developer.md → skills: [..., \"external/skill-name\"]"
echo ""
