#!/bin/bash
set -euo pipefail
source "$(cd "$(dirname "$0")" && pwd)/common.sh"

echo -e "${BOLD}opencode-hub — oc.sh${RESET}"
echo ""
echo -e "${BOLD}Usage:${RESET}"
echo "  ./oc.sh <commande> [arguments]"
echo ""
echo -e "${BOLD}Setup:${RESET}"
echo "  install                       Installe les outils IA et Beads (bd)"
echo "  init [PROJECT_ID] [path]      Initialise ou adopte un projet"
echo "  version                       Affiche la version du hub"
echo ""
echo -e "${BOLD}Projets:${RESET}"
echo "  list                          Liste les projets enregistrés"
echo "  status                        Statut de tous les projets (Beads, API, agents déployés)"
echo "  remove <PROJECT_ID>           Supprime un projet du registre"
echo "  remove <PROJECT_ID> --clean   Supprime + nettoie les fichiers déployés dans le projet"
echo ""
echo -e "${BOLD}Lancement:${RESET}"
echo "  start [PROJECT_ID] [prompt]            Lance l'outil IA"
echo "  start [PROJECT_ID] --dev               Bootstrap tickets ai-delegated (label par défaut)"
echo "  start [PROJECT_ID] --dev --label <l>   Bootstrap tickets filtrés par label"
echo "  start [PROJECT_ID] --dev --assignee <u> Bootstrap tickets filtrés par assignee"
echo "  start [PROJECT_ID] --onboard           Déclenche l'agent onboarder (découverte projet)"
echo ""
echo -e "${BOLD}Maintenance:${RESET}"
echo "  deploy [target] [PROJECT_ID]          Déploie les agents (opencode/claude-code/vscode/all)"
echo "  deploy --check [target] [PROJECT_ID]  Vérifie si les agents déployés sont à jour"
echo "  deploy --diff  [target] [PROJECT_ID]  Diff sources → déployés (propose le deploy si écart)"
echo "  sync                                  Redéploie les agents sur tous les projets enregistrés"
echo "  sync --dry-run                        Vérifie la fraîcheur sur tous les projets (sans déployer)"
echo "  update                                Met à jour les outils installés"
echo ""
echo -e "${BOLD}Configuration API :${RESET}"
echo "  config set <PROJECT_ID> [--model m] [--provider p] [--api-key k] [--base-url u]"
echo "                                       Configure le modèle et la clé API d'un projet"
echo "  config get <PROJECT_ID>              Affiche la configuration d'un projet"
echo "  config list                          Liste toutes les configurations enregistrées"
echo "  config unset <PROJECT_ID>            Supprime la configuration d'un projet"
echo ""
echo -e "${BOLD}Cibles deploy:${RESET}"
echo "  opencode     → .opencode/agents/ + opencode.json"
echo "  claude-code  → .claude/agents/"
echo "  vscode       → .github/copilot-instructions.md + .vscode/prompts/"
echo "  all          → toutes les cibles actives"
echo ""
echo -e "${BOLD}Agents:${RESET}"
echo "  agent list                     Lister les agents canoniques"
echo "  agent create                   Créer un agent (interactif)"
echo "  agent edit <agent-id>          Modifier les skills et métadonnées"
echo "  agent info <agent-id>          Afficher le détail d'un agent"
echo "  agent validate [agent-id]      Valider la cohérence des agents (ou d'un seul)"
echo "  agent keytest                  Diagnostic clavier (octets reçus par touche)"
echo ""
echo -e "${BOLD}Skills externes (context7):${RESET}"
echo "  skills search <query>          Rechercher des skills sur context7"
echo "  skills info /owner/repo        Prévisualiser les skills d'un dépôt"
echo "  skills add /owner/repo [name]  Télécharger et ajouter un skill externe"
echo "  skills list                    Lister tous les skills (locaux + externes)"
echo "  skills update [name]           Mettre à jour un skill externe (ou tous)"
echo "  skills used-by <skill>         Lister les agents qui utilisent ce skill"
echo "  skills sync                    Re-télécharger tous les skills (après clone)"
echo "  skills remove <name>           Supprimer un skill externe"
echo ""
echo -e "${BOLD}Beads (bd) :${RESET}"
echo "  beads status [PROJECT_ID]                Vérifie si Beads est initialisé (tous si sans ID)"
echo "  beads init <PROJECT_ID>                  Initialise .beads/ dans le projet"
echo "  beads list <PROJECT_ID>                  Liste les tickets ouverts du projet"
echo "  beads create <PROJECT_ID> [titre] [--label l] [--type t] [--desc d]"
echo "                                           Crée un ticket (non-interactif si titre fourni)"
echo "  beads open <PROJECT_ID>                  Affiche le chemin pour utiliser bd manuellement"
echo "  beads sync <PROJECT_ID> [--pull-only|--push-only|--dry-run]"
echo "                                           Synchronise avec le tracker externe (Jira/GitLab)"
echo "  beads tracker status <PROJECT_ID>        Affiche le statut de connexion au tracker"
echo "  beads tracker setup  <PROJECT_ID>        Configure le tracker (interactif)"
echo "  beads tracker switch <PROJECT_ID>        Change de provider de tracker"
echo ""
echo -e "${BOLD}Exemples skills:${RESET}"
echo "  ./oc.sh skills search pdf"
echo "  ./oc.sh skills add /owner/repo skill-name"
echo "  Puis dans agents/developer.md → skills: [..., \"external/skill-name\"]"
echo ""
