#!/bin/bash
# Generated by GitHub Copilot
# Créateur et modificateur d'agents canoniques.
# Usage : ./oc.sh agent <commande> [args]

source "$(cd "$(dirname "$0")" && pwd)/common.sh"

EXTERNAL_SKILLS_DIR="$HUB_DIR/skills/external"

# ── HELPERS ──────────────────────────────────────────────────────────────────

##
# Construit la liste de tous les skills disponibles (locaux + externes).
# Imprime un skill par ligne sous la forme "chemin/relatif" (sans .md).
##
_list_all_skills() {
  # Skills locaux
  find "$HUB_DIR/skills" -name "*.md" \
      -not -path "*/external/*" \
      -type f 2>/dev/null | sort \
    | while IFS= read -r f; do
        echo "${f#$HUB_DIR/skills/}" | sed 's/\.md$//'
      done

  # Skills externes
  if [ -d "$EXTERNAL_SKILLS_DIR" ]; then
    find "$EXTERNAL_SKILLS_DIR" -name "*.md" \
        -not -name ".sources.json" \
        -type f 2>/dev/null | sort \
      | while IFS= read -r f; do
          name=$(basename "$f" .md)
          echo "external/$name"
        done
  fi
}

##
# Affiche un menu de sélection de skills et retourne la liste choisie.
# Les skills déjà sélectionnés sont pré-cochés.
# @param {string} $1 — Liste courante (séparée par virgules)
# Écrit la sélection finale sur stdout (séparée par virgules).
##
_pick_skills() {
  local current_csv="${1:-}"

  # Collect all available skills into an indexed array
  local all_skills=()
  while IFS= read -r s; do
    all_skills+=("$s")
  done < <(_list_all_skills)

  if [ ${#all_skills[@]} -eq 0 ]; then
    log_warn "Aucun skill disponible."
    echo "$current_csv"
    return
  fi

  echo ""
  echo -e "${BOLD}Skills disponibles :${RESET}"
  echo "  (Entrez les numéros séparés par des espaces, ex: 1 3 5)"
  echo ""

  # Afficher chaque skill avec son numéro et son état (sélectionné ou non)
  local i=1
  for skill in "${all_skills[@]}"; do
    if echo ",$current_csv," | grep -q ",${skill},"; then
      echo -e "  ${GREEN}[x]${RESET} $i. $skill"
    else
      echo "      $i. $skill"
    fi
    i=$((i + 1))
  done
  echo ""

  read -rp "Numéros des skills à activer (0 = aucun, vide = inchangé) : " selection

  # Si vide, conserver la sélection courante
  if [ -z "$selection" ]; then
    echo "$current_csv"
    return
  fi

  # 0 = vider complètement la liste
  if [ "$selection" = "0" ]; then
    echo ""
    return
  fi

  # Construire la nouvelle liste à partir des indices choisis
  local chosen=()
  for num in $selection; do
    # Valider que c'est un entier dans la plage
    if ! echo "$num" | grep -qE '^[0-9]+$'; then
      log_warn "Numéro invalide ignoré : $num" >&2
      continue
    fi
    if [ "$num" -lt 1 ] || [ "$num" -gt "${#all_skills[@]}" ]; then
      log_warn "Numéro hors plage ignoré : $num" >&2
      continue
    fi
    chosen+=("${all_skills[$((num - 1))]}")
  done

  # Retourner la liste CSV triée sans doublons
  printf '%s\n' "${chosen[@]}" | sort -u | tr '\n' ',' | sed 's/,$//'
}

##
# Sélection de cibles (targets) pour l'agent.
# @param {string} $1 — Valeur courante (CSV)
# Écrit la sélection finale sur stdout.
##
_pick_targets() {
  local current="${1:-opencode, claude-code, vscode}"
  local available=("opencode" "claude-code" "vscode")

  echo ""
  echo -e "${BOLD}Cibles disponibles :${RESET}"
  echo "  (Entrez les numéros séparés par des espaces)"
  echo ""

  local i=1
  for t in "${available[@]}"; do
    if echo "$current" | grep -q "$t"; then
      echo -e "  ${GREEN}[x]${RESET} $i. $t"
    else
      echo "      $i. $t"
    fi
    i=$((i + 1))
  done
  echo ""

  read -rp "Numéros des cibles (laisser vide = toutes) : " selection

  if [ -z "$selection" ]; then
    echo "opencode, claude-code, vscode"
    return
  fi

  local chosen=()
  for num in $selection; do
    if ! echo "$num" | grep -qE '^[0-9]+$'; then continue; fi
    if [ "$num" -lt 1 ] || [ "$num" -gt "${#available[@]}" ]; then continue; fi
    chosen+=("${available[$((num - 1))]}")
  done

  printf '%s\n' "${chosen[@]}" | tr '\n' ', ' | sed 's/, $//'
}

##
# Réécrit le frontmatter d'un agent existant avec de nouvelles valeurs.
# @param {string} $1 — Chemin du fichier agent
# @param {string} $2 — Nouvelle valeur de skills (CSV → format YAML liste inline)
# @param {string} $3 — Nouvelle valeur de targets (CSV → format YAML liste inline)
# @param {string} $4 — Nouveau label
# @param {string} $5 — Nouvelle description
##
_update_frontmatter() {
  local file="$1" skills_csv="$2" targets_csv="$3" label="$4" description="$5"

  # Convertir CSV "a, b, c" en format YAML inline [a, b, c]
  local skills_yaml
  skills_yaml=$(echo "$skills_csv" | sed 's/,\s*/", "/g' | sed 's/^/"/' | sed 's/$/"/' | sed 's/^/[/' | sed 's/$/]/')
  # Nettoyage : [" " "a"] → ["a"]
  skills_yaml=$(printf '%s\n' "$skills_csv" | tr ',' '\n' | sed 's/^ *//' | sed 's/ *$//' | grep -v '^$' | sed 's/.*/"&"/' | tr '\n' ',' | sed 's/,$//' | sed 's/^/[/' | sed 's/$/]/')

  local targets_yaml
  targets_yaml=$(printf '%s\n' "$targets_csv" | tr ',' '\n' | sed 's/^ *//' | sed 's/ *$//' | grep -v '^$' | sed 's/.*/"&"/' | tr '\n' ',' | sed 's/,$//' | sed 's/^/[/' | sed 's/$/]/')

  # Extraire le corps (sans frontmatter)
  local body
  body=$(awk 'BEGIN{f=0;d=0} /^---$/{if(!f){f=1;next}else if(!d){d=1;next}} d{print}' "$file")

  # Reconstruire le fichier avec le nouveau frontmatter
  local agent_id
  agent_id=$(basename "$file" .md)

  cat > "$file" << FRONTMATTER
---
id: ${agent_id}
label: ${label}
description: ${description}
targets: ${targets_yaml}
skills: ${skills_yaml}
---
FRONTMATTER

  # Ré-append le corps en évitant un saut de ligne double
  printf '%s\n' "$body" >> "$file"
}

# ── LIST ─────────────────────────────────────────────────────────────────────

##
# Liste les agents canoniques disponibles dans agents/.
##
cmd_list() {
  log_title "Agents canoniques"
  echo ""

  local found=0
  for f in "$CANONICAL_AGENTS_DIR"/*.md; do
    [ -f "$f" ] || continue
    local id label description targets skills_count
    id=$(grep '^id:' "$f" | head -1 | sed 's/^id:[[:space:]]*//')
    label=$(grep '^label:' "$f" | head -1 | sed 's/^label:[[:space:]]*//')
    description=$(grep '^description:' "$f" | head -1 | sed 's/^description:[[:space:]]*//')
    skills_count=$(grep '^skills:' "$f" | head -1 | tr ',' '\n' | grep -v '^$' | wc -l | tr -d ' ')
    targets=$(grep '^targets:' "$f" | head -1 | sed 's/^targets:[[:space:]]*//')
    echo -e "  ${BOLD}${id}${RESET}  (${label})"
    echo "    → $description"
    echo "    cibles : $targets"
    echo "    skills : $skills_count skill(s) configuré(s)"
    echo ""
    found=1
  done

  [ "$found" -eq 0 ] && echo "  (aucun agent dans agents/)"
}

# ── INFO ─────────────────────────────────────────────────────────────────────

##
# Affiche le détail d'un agent (frontmatter + liste complète des skills).
# @param {string} $1 — Identifiant ou nom de fichier de l'agent
##
cmd_info() {
  local name="${1:-}"
  if [ -z "$name" ]; then
    log_error "Usage : oc agent info <agent-id>"
    exit 1
  fi

  local file="$CANONICAL_AGENTS_DIR/${name}.md"
  [ -f "$file" ] || { log_error "Agent '$name' introuvable dans agents/."; exit 1; }

  log_title "Agent : $name"
  echo ""
  sed -n '/^---$/,/^---$/p' "$file" | grep -v '^---$'
  echo ""
  echo -e "${BOLD}Skills assignés :${RESET}"
  grep '^skills:' "$file" | head -1 \
    | sed 's/^skills:[[:space:]]*//' \
    | tr -d '[]' | tr ',' '\n' \
    | sed 's/^ *//' | sed 's/ *$//' | grep -v '^$' \
    | while IFS= read -r skill; do
        cleaned=$(echo "$skill" | tr -d '"')
        local skill_file="$HUB_DIR/skills/${cleaned}.md"
        if [ -f "$skill_file" ]; then
          echo -e "  ${GREEN}✔${RESET}  $cleaned"
        else
          echo -e "  ${YELLOW}⚠${RESET}  $cleaned  (fichier absent)"
        fi
      done
}

# ── CREATE ───────────────────────────────────────────────────────────────────

##
# Crée un nouvel agent canonique de façon interactive.
##
cmd_create() {
  log_title "Créer un nouvel agent"
  echo ""

  # Identifiant
  read -rp "Identifiant (ex: reviewer) : " agent_id
  agent_id=$(echo "$agent_id" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_-]/-/g')
  if [ -z "$agent_id" ]; then
    log_error "Identifiant requis."
    exit 1
  fi

  local file="$CANONICAL_AGENTS_DIR/${agent_id}.md"
  if [ -f "$file" ]; then
    log_error "L'agent '$agent_id' existe déjà. Utilisez 'oc agent edit $agent_id'."
    exit 1
  fi

  # Label
  read -rp "Label (nom court, ex: CodeReviewer) [${agent_id}] : " label
  label="${label:-$agent_id}"

  # Description
  read -rp "Description : " description
  description="${description:-Assistant $label}"

  # Targets
  local targets_csv
  targets_csv=$(_pick_targets "opencode, claude-code, vscode")
  log_info "Cibles : $targets_csv"

  # Skills
  local skills_csv
  skills_csv=$(_pick_skills "")
  if [ -z "$skills_csv" ]; then
    log_warn "Aucun skill sélectionné."
  else
    log_info "Skills : $skills_csv"
  fi

  # Corps par défaut
  local body
  body=$(cat << BODY

# 🤖 ${label}

${description}

## Ce que tu fais
- TODO : décrire les responsabilités de cet agent

## Workflow
1. TODO : décrire le workflow
BODY
)

  # Construire le frontmatter
  local skills_yaml targets_yaml
  skills_yaml=$(printf '%s\n' "$skills_csv" | tr ',' '\n' | sed 's/^ *//' | sed 's/ *$//' | grep -v '^$' | sed 's/.*/"&"/' | tr '\n' ',' | sed 's/,$//' | sed 's/^/[/' | sed 's/$/]/')
  targets_yaml=$(printf '%s\n' "$targets_csv" | tr ',' '\n' | sed 's/^ *//' | sed 's/ *$//' | grep -v '^$' | sed 's/.*/"&"/' | tr '\n' ',' | sed 's/,$//' | sed 's/^/[/' | sed 's/$/]/')

  # Créer le fichier
  cat > "$file" << FRONTMATTER
---
id: ${agent_id}
label: ${label}
description: ${description}
targets: ${targets_yaml}
skills: ${skills_yaml}
---
FRONTMATTER
  printf '%s\n' "$body" >> "$file"

  echo ""
  log_success "Agent '$agent_id' créé → agents/${agent_id}.md"
  log_info    "Personnalisez le corps dans agents/${agent_id}.md"
  log_info    "Puis déployez : ./oc.sh deploy all"
}

# ── EDIT ─────────────────────────────────────────────────────────────────────

##
# Modifie les métadonnées et les skills d'un agent existant de façon interactive.
# @param {string} $1 — Identifiant de l'agent à modifier
##
cmd_edit() {
  local name="${1:-}"
  if [ -z "$name" ]; then
    log_error "Usage : oc agent edit <agent-id>"
    log_info  "Utilisez 'oc agent list' pour voir les agents disponibles."
    exit 1
  fi

  local file="$CANONICAL_AGENTS_DIR/${name}.md"
  [ -f "$file" ] || { log_error "Agent '$name' introuvable dans agents/."; exit 1; }

  log_title "Modifier l'agent : $name"

  # Lire les valeurs courantes
  local cur_label cur_desc cur_targets cur_skills
  cur_label=$(grep '^label:' "$file" | head -1 | sed 's/^label:[[:space:]]*//')
  cur_desc=$(grep '^description:' "$file" | head -1 | sed 's/^description:[[:space:]]*//')
  cur_targets=$(grep '^targets:' "$file" | head -1 | sed 's/^targets:[[:space:]]*//' | tr -d '[]"')
  cur_skills=$(grep '^skills:' "$file" | head -1 | sed 's/^skills:[[:space:]]*//' | tr -d '[]"')

  echo ""
  echo -e "  label       : ${BOLD}${cur_label}${RESET}"
  echo   "  description : $cur_desc"
  echo   "  targets     : $cur_targets"
  echo   "  skills      : $cur_skills"
  echo ""

  # Label
  read -rp "Nouveau label [${cur_label}] : " new_label
  new_label="${new_label:-$cur_label}"

  # Description
  read -rp "Nouvelle description [${cur_desc}] : " new_desc
  new_desc="${new_desc:-$cur_desc}"

  # Targets
  echo ""
  read -rp "Modifier les cibles ? (y/N) : " edit_targets
  local new_targets="$cur_targets"
  if [[ "$edit_targets" =~ ^[Yy]$ ]]; then
    new_targets=$(_pick_targets "$cur_targets")
    log_info "Cibles : $new_targets"
  fi

  # Skills (toujours proposé)
  local new_skills
  new_skills=$(_pick_skills "$cur_skills")
  if [ -n "$new_skills" ]; then
    log_info "Skills : $new_skills"
  else
    new_skills="$cur_skills"
    log_info "Skills inchangés."
  fi

  # Valider avant écriture
  echo ""
  echo -e "${BOLD}Récapitulatif des modifications :${RESET}"
  echo "  label       : $new_label"
  echo "  description : $new_desc"
  echo "  targets     : $new_targets"
  echo "  skills      : $new_skills"
  echo ""
  read -rp "Appliquer ? (Y/n) : " confirm
  confirm="${confirm:-Y}"
  [[ "$confirm" =~ ^[Yy]$ ]] || { log_info "Annulé."; exit 0; }

  _update_frontmatter "$file" "$new_skills" "$new_targets" "$new_label" "$new_desc"

  echo ""
  log_success "Agent '$name' mis à jour → agents/${name}.md"
  log_info    "Relancez le déploiement pour appliquer : ./oc.sh deploy all"
}

# ── DISPATCH ─────────────────────────────────────────────────────────────────

SUBCOMMAND="${1:-}"
shift 2>/dev/null || true

case "$SUBCOMMAND" in
  list)   cmd_list ;;
  info)   cmd_info "$@" ;;
  create) cmd_create ;;
  edit)   cmd_edit "$@" ;;
  *)
    echo -e "${BOLD}oc agent — Gestion des agents canoniques${RESET}"
    echo ""
    echo "  list              Lister les agents disponibles"
    echo "  info <agent-id>   Afficher le détail d'un agent"
    echo "  create            Créer un nouvel agent (interactif)"
    echo "  edit <agent-id>   Modifier les skills et métadonnées d'un agent"
    echo ""
    echo -e "${BOLD}Exemples :${RESET}"
    echo "  ./oc.sh agent list"
    echo "  ./oc.sh agent create"
    echo "  ./oc.sh agent edit developer"
    echo "  ./oc.sh agent info planner"
    echo ""
    ;;
esac
