#!/bin/bash
# Generated by GitHub Copilot
# Gestion des skills externes (context7, etc.)
# Usage : ./oc.sh skills <commande> [args]

source "$(cd "$(dirname "$0")" && pwd)/common.sh"

EXTERNAL_SKILLS_DIR="$HUB_DIR/skills/external"
SOURCES_FILE="$EXTERNAL_SKILLS_DIR/.sources.json"
# Dossier d'installation universelle ctx7 — utilisé comme relais avant copie locale
UNIVERSAL_SKILLS_DIR="$HOME/.agents/skills"

# ── HELPERS ──────────────────────────────────────────────────────────────────

# Vérifie que npx est disponible (requis pour ctx7)
_require_npx() {
  if ! command -v npx &>/dev/null; then
    log_error "npx n'est pas disponible. Installez Node.js → https://nodejs.org"
    exit 1
  fi
}

# Initialise le dossier external et le fichier de sources s'ils n'existent pas
_init_external() {
  mkdir -p "$EXTERNAL_SKILLS_DIR"
  if [ ! -f "$SOURCES_FILE" ]; then
    echo '{}' > "$SOURCES_FILE"
  fi
}

# Enregistre la provenance d'un skill dans .sources.json
_record_source() {
  local skill_name="$1" repo="$2" downloaded_at="$3"
  if ! command -v jq &>/dev/null; then
    log_warn "jq non disponible — provenance non enregistrée."
    return
  fi
  local tmp
  tmp=$(mktemp)
  jq --arg name "$skill_name" \
     --arg repo "$repo" \
     --arg date "$downloaded_at" \
     '.[$name] = {repo: $repo, downloaded_at: $date}' \
     "$SOURCES_FILE" > "$tmp" && mv "$tmp" "$SOURCES_FILE"
}

# Supprime la provenance d'un skill de .sources.json
_remove_source() {
  local skill_name="$1"
  if ! command -v jq &>/dev/null; then
    return
  fi
  local tmp
  tmp=$(mktemp)
  jq --arg name "$skill_name" 'del(.[$name])' "$SOURCES_FILE" > "$tmp" && mv "$tmp" "$SOURCES_FILE"
}

# ── SEARCH ───────────────────────────────────────────────────────────────────

##
# Recherche des skills sur context7 par mot-clé.
# @param {string} $1 — Terme de recherche
##
cmd_search() {
  local query="${1:-}"
  if [ -z "$query" ]; then
    log_error "Usage : oc skills search <query>"
    log_info  "Exemple : oc skills search pdf"
    exit 1
  fi
  _require_npx
  log_title "Recherche de skills : \"$query\""
  echo ""
  # On autorise un code de retour non-nul (ex: aucun résultat) sans interrompre le script
  npx ctx7 skills search "$query" || true
}

# ── INFO ─────────────────────────────────────────────────────────────────────

##
# Prévisualise les skills disponibles dans un dépôt context7 sans les installer.
# @param {string} $1 — Identifiant du dépôt au format /owner/repo
##
cmd_info() {
  local repo="${1:-}"
  if [ -z "$repo" ]; then
    log_error "Usage : oc skills info /owner/repo"
    log_info  "Exemple : oc skills info /anthropics/skills"
    exit 1
  fi
  _require_npx
  log_title "Skills disponibles dans $repo"
  echo ""
  npx ctx7 skills info "$repo" || true
}

# ── ADD ──────────────────────────────────────────────────────────────────────

##
# Télécharge un skill depuis context7 et l'ajoute dans skills/external/.
# Utilise ctx7 CLI comme relais : install dans ~/.agents/skills/ puis copie locale.
# @param {string} $1 — Identifiant du dépôt au format /owner/repo
# @param {string} $2 — (optionnel) Nom du skill à installer
##
cmd_add() {
  local repo="${1:-}" skill_name="${2:-}"
  if [ -z "$repo" ]; then
    log_error "Usage : oc skills add /owner/repo [skill-name]"
    log_info  "Exemple : oc skills add /anthropics/skills pdf"
    log_info  "Pour voir les skills disponibles : oc skills info /owner/repo"
    exit 1
  fi
  _require_npx
  _init_external

  log_title "Ajout d'un skill externe"

  # Si aucun nom fourni, afficher la liste et demander
  if [ -z "$skill_name" ]; then
    log_info "Skills disponibles dans $repo :"
    echo ""
    npx ctx7 skills info "$repo" 2>/dev/null || true
    echo ""
    read -rp "Nom du skill à installer : " skill_name
    if [ -z "$skill_name" ]; then
      log_error "Nom de skill requis. Annulé."
      exit 1
    fi
  fi

  local dest="$EXTERNAL_SKILLS_DIR/${skill_name}.md"

  # Confirmation si le skill existe déjà localement
  if [ -f "$dest" ]; then
    log_warn "Le skill 'external/${skill_name}' existe déjà."
    read -rp "Écraser ? (y/N) : " confirm
    [[ "$confirm" =~ ^[Yy]$ ]] || { log_info "Annulé."; exit 0; }
  fi

  log_info "Téléchargement de '$skill_name' depuis $repo via ctx7..."
  mkdir -p "$UNIVERSAL_SKILLS_DIR"

  # Le chemin attendu après installation ctx7 --universal
  local installed_file="$UNIVERSAL_SKILLS_DIR/${skill_name}.md"

  # Si déjà présent dans le cache universel, on réutilise (ctx7 peut échouer sinon)
  if [ ! -f "$installed_file" ]; then
    npx ctx7 skills install "$repo" "$skill_name" --universal

    # Fallback : recherche par nom partiel si le fichier n'a pas l'extension .md attendue
    if [ ! -f "$installed_file" ]; then
      installed_file=$(find "$UNIVERSAL_SKILLS_DIR" -iname "${skill_name}.*" -type f 2>/dev/null | head -1)
    fi
  fi

  if [ -z "$installed_file" ] || [ ! -f "$installed_file" ]; then
    log_error "Skill installé mais introuvable dans $UNIVERSAL_SKILLS_DIR"
    log_warn  "Vérifiez manuellement le contenu de ce dossier."
    exit 1
  fi

  # Copie vers skills/external/ — seule cette copie est utilisée par le hub
  cp "$installed_file" "$dest"

  # Enregistrement de la provenance
  local now
  now=$(date +%Y-%m-%d)
  _record_source "$skill_name" "$repo" "$now"

  log_success "Skill '$skill_name' ajouté → skills/external/${skill_name}.md"
  echo ""
  log_info "Pour l'utiliser dans un agent, ajoutez 'external/${skill_name}' à la liste"
  log_info "  skills: de son fichier agents/*.md, puis relancez : ./oc.sh deploy all"
}

# ── LIST ─────────────────────────────────────────────────────────────────────

##
# Liste tous les skills disponibles : locaux (skills/) et externes (skills/external/).
##
cmd_list() {
  log_title "Skills disponibles"
  echo ""

  echo -e "${BOLD}Skills locaux :${RESET}"
  local found_local=0
  while IFS= read -r f; do
    echo "  ${f#$HUB_DIR/skills/}" | sed 's/\.md$//'
    found_local=1
  done < <(find "$HUB_DIR/skills" -name "*.md" -not -path "*/external/*" -type f 2>/dev/null | sort)
  [ "$found_local" -eq 0 ] && echo "  (aucun)"

  echo ""
  echo -e "${BOLD}Skills externes (context7) :${RESET}"
  local found_ext=0
  for f in "$EXTERNAL_SKILLS_DIR"/*.md; do
    [ -f "$f" ] || continue
    local name
    name=$(basename "$f" .md)
    local repo=""
    if [ -f "$SOURCES_FILE" ] && command -v jq &>/dev/null; then
      repo=$(jq -r --arg n "$name" '.[$n].repo // ""' "$SOURCES_FILE")
    fi
    if [ -n "$repo" ]; then
      echo "  external/$name  ← $repo"
    else
      echo "  external/$name"
    fi
    found_ext=1
  done
  [ "$found_ext" -eq 0 ] && echo "  (aucun — utilisez : oc skills add /owner/repo [name])"

  echo ""
}

# ── SYNC ─────────────────────────────────────────────────────────────────────

##
# Re-télécharge tous les skills externes enregistrés dans .sources.json.
# Utile après un git clone (skills/external/ est gitignorés).
##
cmd_sync() {
  _require_npx
  _init_external

  if ! command -v jq &>/dev/null; then
    log_error "jq est requis pour lire les sources enregistrées."
    exit 1
  fi

  if [ ! -f "$SOURCES_FILE" ] || [ "$(cat "$SOURCES_FILE")" = '{}' ]; then
    log_info "Aucun skill externe enregistré. Rien à synchroniser."
    return
  fi

  log_title "Synchronisation des skills externes"
  echo ""

  local count=0
  while IFS= read -r skill_name; do
    [ -z "$skill_name" ] && continue
    local repo
    repo=$(jq -r --arg n "$skill_name" '.[$n].repo' "$SOURCES_FILE")
    log_info "Re-téléchargement : $skill_name depuis $repo..."
    # Forcer le re-téléchargement en supprimant le cache universel
    rm -f "$UNIVERSAL_SKILLS_DIR/${skill_name}.md"
    cmd_add "$repo" "$skill_name"
    count=$((count + 1))
  done < <(jq -r 'keys[]' "$SOURCES_FILE")

  echo ""
  log_success "$count skill(s) synchronisé(s)."
}

# ── REMOVE ───────────────────────────────────────────────────────────────────

##
# Supprime un skill externe du hub (ne supprime pas le cache ~/.agents/skills/).
# @param {string} $1 — Nom du skill à supprimer (sans préfixe external/)
##
cmd_remove() {
  local skill_name="${1:-}"
  if [ -z "$skill_name" ]; then
    log_error "Usage : oc skills remove <skill-name>"
    log_info  "Exemple : oc skills remove pdf"
    log_info  "Utilisez 'oc skills list' pour voir les skills disponibles."
    exit 1
  fi

  # Accepter "external/pdf" ou "pdf"
  skill_name="${skill_name#external/}"

  local dest="$EXTERNAL_SKILLS_DIR/${skill_name}.md"
  if [ ! -f "$dest" ]; then
    log_error "Skill externe '${skill_name}' introuvable."
    log_info  "Utilisez 'oc skills list' pour voir les skills disponibles."
    exit 1
  fi

  read -rp "Supprimer le skill externe '${skill_name}' ? (y/N) : " confirm
  [[ "$confirm" =~ ^[Yy]$ ]] || { log_info "Annulé."; exit 0; }

  rm "$dest"
  [ -f "$SOURCES_FILE" ] && _remove_source "$skill_name"

  log_success "Skill '${skill_name}' supprimé."
  log_info    "N'oubliez pas de le retirer de la liste skills: de vos agents si nécessaire."
}

# ── USED-BY ──────────────────────────────────────────────────────────────────

##
# Liste les agents canoniques qui référencent un skill donné.
# Fonctionne pour les skills locaux et externes (avec ou sans préfixe external/).
# @param {string} $1 — Nom du skill (ex: developer/dev-standards-frontend ou external/pdf)
##
cmd_used_by() {
  local skill="${1:-}"
  if [ -z "$skill" ]; then
    log_error "Usage : oc skills used-by <skill>"
    log_info  "Exemples :"
    log_info  "  oc skills used-by developer/dev-standards-frontend"
    log_info  "  oc skills used-by external/pdf"
    exit 1
  fi

  log_title "Agents utilisant le skill : $skill"
  echo ""

  local found=0
  for agent_file in "$CANONICAL_AGENTS_DIR"/*.md; do
    [ -f "$agent_file" ] || continue
    local skills_line
    skills_line=$(grep '^skills:' "$agent_file" | head -1 | tr -d '[]"')
    # Normaliser les espaces autour des virgules pour une recherche fiable
    if echo "$skills_line" | tr ',' '\n' | sed 's/^ *//' | sed 's/ *$//' | grep -qxF "$skill"; then
      local agent_id
      agent_id=$(basename "$agent_file" .md)
      echo -e "  ${GREEN}✔${RESET}  $agent_id  (agents/${agent_id}.md)"
      found=1
    fi
  done

  if [ "$found" -eq 0 ]; then
    echo "  (aucun agent n'utilise ce skill)"
  fi
  echo ""
}

# ── UPDATE ────────────────────────────────────────────────────────────────────

##
# Télécharge la version à jour d'un skill externe depuis sa source ctx7,
# affiche un diff et demande confirmation avant d'écraser.
# Sans argument → met à jour tous les skills externes enregistrés.
# @param {string} $1 — (optionnel) Nom du skill à mettre à jour
##
cmd_update() {
  _require_npx
  _init_external

  if ! command -v jq &>/dev/null; then
    log_error "jq est requis pour lire les sources enregistrées."
    exit 1
  fi

  if [ ! -f "$SOURCES_FILE" ] || [ "$(cat "$SOURCES_FILE")" = '{}' ]; then
    log_info "Aucun skill externe enregistré. Rien à mettre à jour."
    return
  fi

  local target_skill="${1:-}"
  local skills_to_update=()

  if [ -n "$target_skill" ]; then
    # Accepter "external/pdf" ou "pdf"
    target_skill="${target_skill#external/}"
    if ! jq -e --arg n "$target_skill" 'has($n)' "$SOURCES_FILE" &>/dev/null; then
      log_error "Skill externe '$target_skill' non trouvé dans .sources.json"
      log_info  "Utilisez 'oc skills list' pour voir les skills enregistrés."
      exit 1
    fi
    skills_to_update=("$target_skill")
  else
    while IFS= read -r s; do
      [ -n "$s" ] && skills_to_update+=("$s")
    done < <(jq -r 'keys[]' "$SOURCES_FILE")
  fi

  log_title "Mise à jour des skills externes"
  echo ""

  local updated=0 skipped=0
  for skill_name in "${skills_to_update[@]}"; do
    local repo dest tmp_file
    repo=$(jq -r --arg n "$skill_name" '.[$n].repo' "$SOURCES_FILE")
    dest="$EXTERNAL_SKILLS_DIR/${skill_name}.md"

    log_info "Vérification de '$skill_name' depuis $repo..."

    # Télécharger dans un fichier temporaire pour comparer
    tmp_file=$(mktemp /tmp/oc-skill-update-XXXXXX.md)
    # Supprimer le cache universel pour forcer le re-téléchargement
    rm -f "$UNIVERSAL_SKILLS_DIR/${skill_name}.md"

    # Installer silencieusement dans ~/.agents/skills/
    if ! npx ctx7 skills install "$repo" "$skill_name" --universal &>/dev/null; then
      log_warn "Échec du téléchargement de '$skill_name'. Ignoré."
      rm -f "$tmp_file"
      skipped=$((skipped + 1))
      continue
    fi

    local cached="$UNIVERSAL_SKILLS_DIR/${skill_name}.md"
    if [ ! -f "$cached" ]; then
      cached=$(find "$UNIVERSAL_SKILLS_DIR" -iname "${skill_name}.*" -type f 2>/dev/null | head -1)
    fi

    if [ -z "$cached" ] || [ ! -f "$cached" ]; then
      log_warn "Fichier téléchargé introuvable pour '$skill_name'. Ignoré."
      rm -f "$tmp_file"
      skipped=$((skipped + 1))
      continue
    fi

    cp "$cached" "$tmp_file"

    # Comparer avec la version locale
    if [ -f "$dest" ] && diff -q "$dest" "$tmp_file" &>/dev/null; then
      log_success "'$skill_name' est déjà à jour."
      rm -f "$tmp_file"
      skipped=$((skipped + 1))
      continue
    fi

    # Afficher le diff
    echo ""
    echo -e "${BOLD}Diff pour '$skill_name' :${RESET}"
    echo "  (- ancienne version  /  + nouvelle version)"
    echo ""
    diff "$dest" "$tmp_file" | head -60 || true
    echo ""

    read -rp "Appliquer la mise à jour pour '$skill_name' ? (Y/n) : " confirm
    confirm="${confirm:-Y}"
    if [[ "$confirm" =~ ^[Yy]$ ]]; then
      cp "$tmp_file" "$dest"
      local now
      now=$(date +%Y-%m-%d)
      _record_source "$skill_name" "$repo" "$now"
      log_success "'$skill_name' mis à jour."
      updated=$((updated + 1))

      # Lister les agents impactés
      local agents_impacted=()
      for agent_file in "$CANONICAL_AGENTS_DIR"/*.md; do
        [ -f "$agent_file" ] || continue
        local skills_line
        skills_line=$(grep '^skills:' "$agent_file" | head -1 | tr -d '[]"')
        if echo "$skills_line" | tr ',' '\n' | sed 's/^ *//' | sed 's/ *$//' | grep -qxF "external/$skill_name"; then
          agents_impacted+=("$(basename "$agent_file" .md)")
        fi
      done

      if [ ${#agents_impacted[@]} -gt 0 ]; then
        echo -e "  ${YELLOW}⚠${RESET}  Agents impactés : ${agents_impacted[*]}"
        echo -e "  ${YELLOW}⚠${RESET}  Relancez : ./oc.sh deploy all"
      fi
    else
      log_info "Mise à jour de '$skill_name' ignorée."
      skipped=$((skipped + 1))
    fi

    rm -f "$tmp_file"
    echo ""
  done

  echo ""
  [ "$updated" -gt 0 ] && log_success "$updated skill(s) mis à jour."
  [ "$skipped" -gt 0 ] && log_info    "$skipped skill(s) inchangé(s) ou ignoré(s)."
}

# ── DISPATCH ─────────────────────────────────────────────────────────────────

SUBCOMMAND="${1:-}"
shift 2>/dev/null || true

case "$SUBCOMMAND" in
  search)  cmd_search "$@" ;;
  info)    cmd_info "$@" ;;
  add)     cmd_add "$@" ;;
  list)    cmd_list ;;
  sync)    cmd_sync ;;
  update)  cmd_update "$@" ;;
  used-by) cmd_used_by "$@" ;;
  remove)  cmd_remove "$@" ;;
  *)
    echo -e "${BOLD}oc skills — Gestion des skills externes${RESET}"
    echo ""
    echo "  search <query>             Rechercher des skills sur context7"
    echo "  info /owner/repo           Prévisualiser les skills d'un dépôt"
    echo "  add /owner/repo [name]     Ajouter un skill externe"
    echo "  list                       Lister tous les skills (locaux + externes)"
    echo "  update [name]              Mettre à jour un skill externe (ou tous)"
    echo "  used-by <skill>            Lister les agents qui utilisent ce skill"
    echo "  sync                       Re-télécharger tous les skills (après clone)"
    echo "  remove <name>              Supprimer un skill externe"
    echo ""
    echo -e "${BOLD}Exemples :${RESET}"
    echo "  ./oc.sh skills update pdf"
    echo "  ./oc.sh skills update"
    echo "  ./oc.sh skills used-by external/pdf"
    echo "  ./oc.sh skills used-by developer/dev-standards-frontend"
    echo ""
    ;;
esac
