#!/bin/bash
source "$(cd "$(dirname "$0")" && pwd)/common.sh"

echo -e "${BOLD}opencode-hub — oc.sh${RESET}"
echo ""
echo -e "${BOLD}Usage:${RESET}"
echo "  ./oc.sh <commande> [arguments]"
echo ""
echo -e "${BOLD}Setup:${RESET}"
echo "  install                       Installe OpenCode et Beads"
echo "  init [PROJECT_ID] [path]      Initialise ou adopte un projet"
echo ""
echo -e "${BOLD}Projets:${RESET}"
echo "  list                          Liste les projets enregistrés"
echo "  remove <PROJECT_ID>           Supprime un projet du registre"
echo ""
echo -e "${BOLD}Lancement:${RESET}"
echo "  start [PROJECT_ID] [prompt]   Lance OpenCode sur un projet"
echo ""
echo -e "${BOLD}Maintenance:${RESET}"
echo "  sync                          Injecte les skills dans les agents"
echo "  update                        Met à jour OpenCode et Beads"
echo ""
