#!/bin/bash
# Generated by GitHub Copilot
set -euo pipefail
source "$(cd "$(dirname "$0")" && pwd)/common.sh"
source "$LIB_DIR/adapter-manager.sh"

log_title "Installation de opencode-hub"

OS=$(detect_os)
log_info "OS détecté : $OS"

# ── Vérifier jq ─────────────────────────
if ! command -v jq &>/dev/null; then
  log_warn "jq non détecté — dépendance critique pour opencode-hub"
  if [ "$OS" = "macos" ] && command -v brew &>/dev/null; then
    read -rp "  Installer jq via Homebrew ? [Y/n] : " jq_choice
    if [[ "${jq_choice:-Y}" =~ ^[Yy]$ ]]; then
      brew install jq && log_success "jq installé" || log_error "Échec installation jq — à installer manuellement"
    else
      log_warn "Certaines fonctionnalités (deploy, skills, beads) seront dégradées sans jq"
    fi
  else
    log_warn "Installer jq manuellement :"
    log_info "  macOS  : brew install jq"
    log_info "  Ubuntu : sudo apt-get install jq"
    log_info "  Autre  : https://jqlang.github.io/jq/download/"
  fi
else
  log_success "jq $(jq --version)"
fi

# ── Choisir les cibles ───────────────────
log_title "Cibles à configurer"
echo ""
echo "  1. OpenCode (recommandé)"
echo "  2. Claude Code"
echo "  3. VS Code / Copilot"
echo "  4. Tout"
echo ""
read -rp "Choisir (1-4, défaut: 1) : " tool_choice
tool_choice="${tool_choice:-1}"

active_targets=()
case "$tool_choice" in
  2) active_targets=("claude-code") ;;
  3) active_targets=("vscode") ;;
  4) active_targets=("opencode" "claude-code" "vscode") ;;
  *) active_targets=("opencode") ;;
esac

echo ""

# ── Vérifier si une cible requiert Node.js ───────────────────────────────────
needs_node=false
for target in "${active_targets[@]}"; do
  load_adapter "$target"
  adapter_needs_node && needs_node=true && break
done

if [ "$needs_node" = true ]; then
  source "$LIB_DIR/node-installer.sh"
  ensure_node || exit 1
fi

# ── Dossiers requis ──────────────────────
mkdir -p "$HUB_DIR/projects" "$HUB_DIR/skills" "$HUB_DIR/agents" \
         "$HUB_DIR/.opencode/agents" "$HUB_DIR/config" \
         "$HUB_DIR/scripts/lib" "$HUB_DIR/scripts/adapters"

# ── Écrire config/hub.json ───────────────
targets_json=$(printf '"%s",' "${active_targets[@]}" | sed 's/,$//')
cat > "$HUB_DIR/config/hub.json" << HUBJSON
{
  "version": "2.0.0",
  "default_target": "${active_targets[0]}",
  "active_targets": [${targets_json}],
  "opencode": {
    "model": "claude-sonnet-4-5"
  },
  "vscode": {
    "global_skills": [
      "developer/dev-standards-universal",
      "developer/dev-standards-frontend-a11y"
    ]
  }
}
HUBJSON
log_success "config/hub.json mis à jour (cibles : ${active_targets[*]})"

# ── Installer chaque cible sélectionnée ──
for target in "${active_targets[@]}"; do
  load_adapter "$target"
  adapter_install
done

# ── Fichiers initiaux ────────────────────
ensure_projects_file
log_success "projects.md prêt"

if [ ! -f "$PATHS_FILE" ]; then
  echo "# Chemins locaux (ignoré par git)" > "$PATHS_FILE"
  log_success "paths.local.md créé"
fi

echo ""
log_info "Tip : Enrichissez vos agents avec des skills tiers via context7 :"
log_info "  ./oc.sh skills search <query>        # Rechercher"
log_info "  ./oc.sh skills add /owner/repo name  # Ajouter"

# ── Installer Beads (bd) ─────────────────
echo ""
log_title "Installation de Beads (bd)"
if command -v bd &>/dev/null; then
  bd_version=$(bd --version 2>/dev/null || bd version 2>/dev/null || echo '?')
  log_success "Beads déjà installé ($bd_version)"
else
  if command -v brew &>/dev/null; then
    log_info "Installation de bd via Homebrew..."
    brew install bd && log_success "Beads installé" \
      || log_warn "Échec de l'installation via Homebrew"
  else
    log_warn "Homebrew non disponible — installation manuelle requise"
    log_info "  macOS  : brew install bd"
    log_info "  Linux  : voir https://beads.sh/install"
  fi
fi

echo ""
log_success "opencode-hub prêt !"
