#!/bin/bash
# Generated by GitHub Copilot
source "$(cd "$(dirname "$0")" && pwd)/common.sh"
source "$LIB_DIR/adapter-manager.sh"

log_title "Installation de opencode-hub"

OS=$(detect_os)
log_info "OS détecté : $OS"

# ── Node.js ──────────────────────────────
if ! command -v node &>/dev/null; then
  log_error "Node.js n'est pas installé → https://nodejs.org"
  exit 1
fi
log_success "Node.js $(node -v) détecté"

# ── OpenCode ─────────────────────────────
if ! command -v opencode &>/dev/null; then
  log_info "Installation de OpenCode..."
  npm install -g opencode-ai
  log_success "OpenCode installé"
else
  log_success "OpenCode déjà installé ($(opencode --version 2>/dev/null || echo '?'))"
fi

# ── Beads ────────────────────────────────
if ! command -v beads &>/dev/null; then
  log_info "Installation de Beads..."
  npm install -g @beads/cli
  log_success "Beads installé"
else
  log_success "Beads déjà installé"
fi

# ── Dossiers requis ──────────────────────
mkdir -p "$HUB_DIR/projects" "$HUB_DIR/skills" "$HUB_DIR/agents" \
         "$HUB_DIR/.opencode/agents" "$HUB_DIR/config" \
         "$HUB_DIR/scripts/lib" "$HUB_DIR/scripts/adapters"

# ── Choisir les cibles ───────────────────
log_title "Cibles à configurer"
echo ""
echo "  1. OpenCode (recommandé)"
echo "  2. Claude Code"
echo "  3. VS Code / Copilot"
echo "  4. Tout"
echo ""
read -rp "Choisir (1-4, défaut: 1) : " tool_choice
tool_choice="${tool_choice:-1}"

active_targets=()
case "$tool_choice" in
  2) active_targets=("claude-code") ;;
  3) active_targets=("vscode") ;;
  4) active_targets=("opencode" "claude-code" "vscode") ;;
  *) active_targets=("opencode") ;;
esac

# Écrire config/hub.json
targets_json=$(printf '"%s",' "${active_targets[@]}" | sed 's/,$//')
cat > "$HUB_DIR/config/hub.json" << HUBJSON
{
  "version": "2.0.0",
  "default_target": "${active_targets[0]}",
  "active_targets": [${targets_json}]
}
HUBJSON
log_success "config/hub.json mis à jour (cibles : ${active_targets[*]})"

# Installer chaque cible sélectionnée
for target in "${active_targets[@]}"; do
  load_adapter "$target"
  adapter_install
done

# ── Fichiers initiaux ────────────────────
if [ ! -f "$PROJECTS_FILE" ]; then
  echo "# Projets" > "$PROJECTS_FILE"
  log_success "projects.md créé"
fi

if [ ! -f "$PATHS_FILE" ]; then
  echo "# Chemins locaux (ignoré par git)" > "$PATHS_FILE"
  log_success "paths.local.md créé"
fi

echo ""
log_success "opencode-hub prêt !"
