#!/bin/bash
# Generated by GitHub Copilot
source "$(cd "$(dirname "$0")" && pwd)/common.sh"
source "$LIB_DIR/adapter-manager.sh"

TARGET="${1:-}"
PROJECT_ID="${2:-}"

log_title "Déploiement des agents"

# Résoudre les cibles
if [ -z "$TARGET" ] || [ "$TARGET" = "all" ]; then
  targets=()
  while IFS= read -r t; do targets+=("$t"); done < <(get_active_targets)
else
  targets=("$TARGET")
fi

# Résoudre le dossier de déploiement
if [ -n "$PROJECT_ID" ]; then
  PROJECT_ID=$(echo "$PROJECT_ID" | tr '[:lower:]' '[:upper:]')
  if ! project_exists "$PROJECT_ID"; then
    log_error "Projet $PROJECT_ID introuvable → oc list"
    exit 1
  fi
  deploy_dir=$(get_project_path "$PROJECT_ID")
  deploy_dir="${deploy_dir/#\~/$HOME}"
  [ -d "$deploy_dir" ] || { log_error "Dossier introuvable : $deploy_dir"; exit 1; }
  log_info "Projet cible : $PROJECT_ID ($deploy_dir)"
else
  deploy_dir="$HUB_DIR"
  log_info "Déploiement au niveau du hub"
fi

echo ""

for target in "${targets[@]}"; do
  log_info "── Cible : $target"
  load_adapter "$target"
  adapter_validate || { log_error "Cible $target non disponible — déploiement ignoré"; echo ""; continue; }
  adapter_deploy "$deploy_dir"
  echo ""
done

log_success "Déploiement terminé"
