#!/bin/bash
# Generated by GitHub Copilot
# Créateur et modificateur d'agents canoniques.
# Usage : ./oc.sh agent <commande> [args]

source "$(cd "$(dirname "$0")" && pwd)/common.sh"

# EXTERNAL_SKILLS_DIR est défini dans common.sh

# ── HELPERS ──────────────────────────────────────────────────────────────────

##
# Construit la liste de tous les skills disponibles (locaux + externes).
# Imprime un skill par ligne sous la forme "chemin/relatif" (sans .md).
##
_list_all_skills() {
  # Skills locaux
  find "$HUB_DIR/skills" -name "*.md" \
      -not -path "*/external/*" \
      -type f 2>/dev/null | sort \
    | while IFS= read -r f; do
        echo "${f#$HUB_DIR/skills/}" | sed 's/\.md$//'
      done

  # Skills externes
  if [ -d "$EXTERNAL_SKILLS_DIR" ]; then
    find "$EXTERNAL_SKILLS_DIR" -name "*.md" \
        -not -name ".sources.json" \
        -type f 2>/dev/null | sort \
      | while IFS= read -r f; do
          name=$(basename "$f" .md)
          echo "external/$name"
        done
  fi
}

##
# Affiche une page de skills avec numéros globaux, état sélectionné, et description.
# @param {array nameref} $1 — all_skills[]
# @param {array nameref} $2 — selected[] (indices 0-based actifs)
# @param {int}           $3 — page courante (0-based)
# @param {int}           $4 — taille de page
##
_print_skills_page() {
  local -n _ps_skills=$1
  local -n _ps_sel=$2
  local page=$3 page_size=$4
  local total=${#_ps_skills[@]}
  local total_pages=$(( (total + page_size - 1) / page_size ))
  local start=$(( page * page_size ))
  local end=$(( start + page_size ))
  [ "$end" -gt "$total" ] && end=$total

  echo "" >&2
  echo -e "${BOLD}Skills disponibles — page $((page+1))/$total_pages${RESET}  (total : $total)" >&2
  echo "" >&2

  for (( i=start; i<end; i++ )); do
    local skill="${_ps_skills[$i]}"
    local num=$((i + 1))
    local desc=""
    local skill_file="$HUB_DIR/skills/${skill}.md"
    [ -f "$skill_file" ] && desc=$(grep '^description:' "$skill_file" | head -1 | sed 's/^description:[[:space:]]*//')

    # Vérifie si l'indice est dans la sélection active
    local selected=0
    for s in "${_ps_sel[@]}"; do
      [ "$s" -eq "$i" ] && selected=1 && break
    done

    if [ "$selected" -eq 1 ]; then
      printf "  ${GREEN}[x]${RESET} %3d. %-50s" "$num" "$skill" >&2
    else
      printf "      %3d. %-50s" "$num" "$skill" >&2
    fi
    [ -n "$desc" ] && printf "  ${BLUE}%s${RESET}" "$desc" >&2
    echo "" >&2
  done

  echo "" >&2
  local nav=""
  [ "$page" -gt 0 ]               && nav+="[p] précédent  "
  [ "$page" -lt $((total_pages-1)) ] && nav+="[n] suivant  "
  nav+="[numéros] sélectionner  [0] vider  [entrée] valider"
  echo -e "  $nav" >&2
  echo "" >&2
}

##
# Affiche un menu de sélection de skills avec pagination et retourne la liste choisie.
# Les skills déjà sélectionnés sont pré-cochés.
# @param {string} $1 — Liste courante (séparée par virgules)
# Écrit la sélection finale sur stdout (séparée par virgules).
##
_pick_skills() {
  local current_csv="${1:-}"
  local page_size=10

  # Charger tous les skills
  local all_skills=()
  while IFS= read -r s; do
    all_skills+=("$s")
  done < <(_list_all_skills)

  if [ ${#all_skills[@]} -eq 0 ]; then
    log_warn "Aucun skill disponible." >&2
    echo "$current_csv"
    return
  fi

  # Initialiser la sélection courante (indices 0-based)
  local selected=()
  for (( i=0; i<${#all_skills[@]}; i++ )); do
    local skill="${all_skills[$i]}"
    if echo ",$current_csv," | grep -q ",${skill},"; then
      selected+=("$i")
    fi
  done

  local page=0
  local total_pages=$(( (${#all_skills[@]} + page_size - 1) / page_size ))

  while true; do
    _print_skills_page all_skills selected "$page" "$page_size"

    read -rp "  > " input </dev/tty

    case "$input" in
      n|N)
        [ "$page" -lt $((total_pages-1)) ] && page=$((page+1)) || echo -e "  ${YELLOW}Déjà sur la dernière page.${RESET}" >&2
        ;;
      p|P)
        [ "$page" -gt 0 ] && page=$((page-1)) || echo -e "  ${YELLOW}Déjà sur la première page.${RESET}" >&2
        ;;
      "")
        # Valider — sortir de la boucle
        break
        ;;
      0)
        # Vider la sélection
        selected=()
        echo -e "  ${YELLOW}Sélection vidée.${RESET}" >&2
        ;;
      *)
        # Traiter les numéros saisis
        local changed=0
        for num in $input; do
          if ! echo "$num" | grep -qE '^[0-9]+$'; then
            echo -e "  ${YELLOW}Numéro invalide ignoré : $num${RESET}" >&2
            continue
          fi
          local idx=$(( num - 1 ))
          if [ "$idx" -lt 0 ] || [ "$idx" -ge "${#all_skills[@]}" ]; then
            echo -e "  ${YELLOW}Numéro hors plage ignoré : $num${RESET}" >&2
            continue
          fi
          # Toggle : retirer si déjà présent, ajouter sinon
          local found=0
          local new_sel=()
          for s in "${selected[@]}"; do
            if [ "$s" -eq "$idx" ]; then
              found=1
            else
              new_sel+=("$s")
            fi
          done
          if [ "$found" -eq 0 ]; then
            new_sel+=("$idx")
          fi
          selected=("${new_sel[@]}")
          changed=1
        done
        ;;
    esac
  done

  # Construire la liste CSV finale (dans l'ordre des indices)
  local chosen=()
  # Trier les indices sélectionnés
  local sorted_sel
  sorted_sel=$(printf '%s\n' "${selected[@]}" | sort -n)
  while IFS= read -r idx; do
    [ -z "$idx" ] && continue
    chosen+=("${all_skills[$idx]}")
  done <<< "$sorted_sel"

  printf '%s\n' "${chosen[@]}" | tr '\n' ',' | sed 's/,$//'
}

##
# Sélection de cibles (targets) pour l'agent.
# @param {string} $1 — Valeur courante (CSV)
# Écrit la sélection finale sur stdout.
##
_pick_targets() {
  local current="${1:-opencode, claude-code, vscode}"
  local available=("opencode" "claude-code" "vscode")

  echo ""
  echo -e "${BOLD}Cibles disponibles :${RESET}"
  echo "  (Entrez les numéros séparés par des espaces)"
  echo ""

  local i=1
  for t in "${available[@]}"; do
    if echo "$current" | grep -q "$t"; then
      echo -e "  ${GREEN}[x]${RESET} $i. $t"
    else
      echo "      $i. $t"
    fi
    i=$((i + 1))
  done
  echo ""

  read -rp "Numéros des cibles (laisser vide = toutes) : " selection

  if [ -z "$selection" ]; then
    echo "opencode, claude-code, vscode"
    return
  fi

  local chosen=()
  for num in $selection; do
    if ! echo "$num" | grep -qE '^[0-9]+$'; then continue; fi
    if [ "$num" -lt 1 ] || [ "$num" -gt "${#available[@]}" ]; then continue; fi
    chosen+=("${available[$((num - 1))]}")
  done

  printf '%s\n' "${chosen[@]}" | tr '\n' ', ' | sed 's/, $//'
}

##
# Réécrit le frontmatter d'un agent existant avec de nouvelles valeurs.
# @param {string} $1 — Chemin du fichier agent
# @param {string} $2 — Nouvelle valeur de skills (CSV → format YAML liste inline)
# @param {string} $3 — Nouvelle valeur de targets (CSV → format YAML liste inline)
# @param {string} $4 — Nouveau label
# @param {string} $5 — Nouvelle description
##
_update_frontmatter() {
  local file="$1" skills_csv="$2" targets_csv="$3" label="$4" description="$5"

  # Convertir CSV en format YAML inline ["a", "b", "c"]
  local skills_yaml
  skills_yaml=$(printf '%s\n' "$skills_csv" | tr ',' '\n' | sed 's/^ *//' | sed 's/ *$//' | grep -v '^$' | sed 's/.*/"&"/' | tr '\n' ',' | sed 's/,$//' | sed 's/^/[/' | sed 's/$/]/')

  local targets_yaml
  targets_yaml=$(printf '%s\n' "$targets_csv" | tr ',' '\n' | sed 's/^ *//' | sed 's/ *$//' | grep -v '^$' | sed 's/.*/"&"/' | tr '\n' ',' | sed 's/,$//' | sed 's/^/[/' | sed 's/$/]/')

  # Extraire le corps (sans frontmatter)
  local body
  body=$(awk 'BEGIN{f=0;d=0} /^---$/{if(!f){f=1;next}else if(!d){d=1;next}} d{print}' "$file")

  # Reconstruire le fichier avec le nouveau frontmatter
  local agent_id
  agent_id=$(basename "$file" .md)

  cat > "$file" << FRONTMATTER
---
id: ${agent_id}
label: ${label}
description: ${description}
targets: ${targets_yaml}
skills: ${skills_yaml}
---
FRONTMATTER

  # Ré-append le corps en évitant un saut de ligne double
  printf '%s\n' "$body" >> "$file"
}

# ── LIST ─────────────────────────────────────────────────────────────────────

##
# Liste les agents canoniques disponibles dans agents/.
##
cmd_list() {
  log_title "Agents canoniques"
  echo ""

  local found=0
  for f in "$CANONICAL_AGENTS_DIR"/*.md; do
    [ -f "$f" ] || continue
    local id label description targets skills_count
    id=$(grep '^id:' "$f" | head -1 | sed 's/^id:[[:space:]]*//')
    label=$(grep '^label:' "$f" | head -1 | sed 's/^label:[[:space:]]*//')
    description=$(grep '^description:' "$f" | head -1 | sed 's/^description:[[:space:]]*//')
    skills_count=$(grep '^skills:' "$f" | head -1 | tr ',' '\n' | grep -v '^$' | wc -l | tr -d ' ')
    targets=$(grep '^targets:' "$f" | head -1 | sed 's/^targets:[[:space:]]*//')
    echo -e "  ${BOLD}${id}${RESET}  (${label})"
    echo "    → $description"
    echo "    cibles : $targets"
    echo "    skills : $skills_count skill(s) configuré(s)"
    echo ""
    found=1
  done

  [ "$found" -eq 0 ] && echo "  (aucun agent dans agents/)"
}

# ── INFO ─────────────────────────────────────────────────────────────────────

##
# Affiche le détail d'un agent (frontmatter + liste complète des skills).
# @param {string} $1 — Identifiant ou nom de fichier de l'agent
##
cmd_info() {
  local name="${1:-}"
  if [ -z "$name" ]; then
    log_error "Usage : oc agent info <agent-id>"
    exit 1
  fi

  local file="$CANONICAL_AGENTS_DIR/${name}.md"
  [ -f "$file" ] || { log_error "Agent '$name' introuvable dans agents/."; exit 1; }

  log_title "Agent : $name"
  echo ""
  sed -n '/^---$/,/^---$/p' "$file" | grep -v '^---$'
  echo ""
  echo -e "${BOLD}Skills assignés :${RESET}"
  grep '^skills:' "$file" | head -1 \
    | sed 's/^skills:[[:space:]]*//' \
    | tr -d '[]' | tr ',' '\n' \
    | sed 's/^ *//' | sed 's/ *$//' | grep -v '^$' \
    | while IFS= read -r skill; do
        cleaned=$(echo "$skill" | tr -d '"')
        local skill_file="$HUB_DIR/skills/${cleaned}.md"
        if [ -f "$skill_file" ]; then
          echo -e "  ${GREEN}✔${RESET}  $cleaned"
        else
          echo -e "  ${YELLOW}⚠${RESET}  $cleaned  (fichier absent)"
        fi
      done
}

# ── CREATE ───────────────────────────────────────────────────────────────────

##
# Crée un nouvel agent canonique de façon interactive.
##
cmd_create() {
  log_title "Créer un nouvel agent"
  echo ""

  # Identifiant
  read -rp "Identifiant (ex: reviewer) : " agent_id
  agent_id=$(echo "$agent_id" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_-]/-/g')
  if [ -z "$agent_id" ]; then
    log_error "Identifiant requis."
    exit 1
  fi

  local file="$CANONICAL_AGENTS_DIR/${agent_id}.md"
  if [ -f "$file" ]; then
    log_error "L'agent '$agent_id' existe déjà. Utilisez 'oc agent edit $agent_id'."
    exit 1
  fi

  # Label
  read -rp "Label (nom court, ex: CodeReviewer) [${agent_id}] : " label
  label="${label:-$agent_id}"

  # Description
  read -rp "Description : " description
  description="${description:-Assistant $label}"

  # Targets
  local targets_csv
  targets_csv=$(_pick_targets "opencode, claude-code, vscode")
  log_info "Cibles : $targets_csv"

  # Skills
  local skills_csv
  skills_csv=$(_pick_skills "")
  if [ -z "$skills_csv" ]; then
    log_warn "Aucun skill sélectionné."
  else
    log_info "Skills : $skills_csv"
  fi

  # Corps par défaut
  local body
  body=$(cat << BODY

# 🤖 ${label}

${description}

## Ce que tu fais
- TODO : décrire les responsabilités de cet agent

## Workflow
1. TODO : décrire le workflow
BODY
)

  # Construire le frontmatter
  local skills_yaml targets_yaml
  skills_yaml=$(printf '%s\n' "$skills_csv" | tr ',' '\n' | sed 's/^ *//' | sed 's/ *$//' | grep -v '^$' | sed 's/.*/"&"/' | tr '\n' ',' | sed 's/,$//' | sed 's/^/[/' | sed 's/$/]/')
  targets_yaml=$(printf '%s\n' "$targets_csv" | tr ',' '\n' | sed 's/^ *//' | sed 's/ *$//' | grep -v '^$' | sed 's/.*/"&"/' | tr '\n' ',' | sed 's/,$//' | sed 's/^/[/' | sed 's/$/]/')

  # Créer le fichier
  cat > "$file" << FRONTMATTER
---
id: ${agent_id}
label: ${label}
description: ${description}
targets: ${targets_yaml}
skills: ${skills_yaml}
---
FRONTMATTER
  printf '%s\n' "$body" >> "$file"

  echo ""
  log_success "Agent '$agent_id' créé → agents/${agent_id}.md"
  log_info    "Personnalisez le corps dans agents/${agent_id}.md"
  log_info    "Puis déployez : ./oc.sh deploy all"
}

# ── EDIT ─────────────────────────────────────────────────────────────────────

##
# Modifie les métadonnées et les skills d'un agent existant de façon interactive.
# @param {string} $1 — Identifiant de l'agent à modifier
##
cmd_edit() {
  local name="${1:-}"
  if [ -z "$name" ]; then
    log_error "Usage : oc agent edit <agent-id>"
    log_info  "Utilisez 'oc agent list' pour voir les agents disponibles."
    exit 1
  fi

  local file="$CANONICAL_AGENTS_DIR/${name}.md"
  [ -f "$file" ] || { log_error "Agent '$name' introuvable dans agents/."; exit 1; }

  log_title "Modifier l'agent : $name"

  # Lire les valeurs courantes
  local cur_label cur_desc cur_targets cur_skills
  cur_label=$(grep '^label:' "$file" | head -1 | sed 's/^label:[[:space:]]*//')
  cur_desc=$(grep '^description:' "$file" | head -1 | sed 's/^description:[[:space:]]*//')
  cur_targets=$(grep '^targets:' "$file" | head -1 | sed 's/^targets:[[:space:]]*//' | tr -d '[]"')
  cur_skills=$(grep '^skills:' "$file" | head -1 | sed 's/^skills:[[:space:]]*//' | tr -d '[]"')

  echo ""
  echo -e "  label       : ${BOLD}${cur_label}${RESET}"
  echo   "  description : $cur_desc"
  echo   "  targets     : $cur_targets"
  echo   "  skills      : $cur_skills"
  echo ""

  # Label
  read -rp "Nouveau label [${cur_label}] : " new_label
  new_label="${new_label:-$cur_label}"

  # Description
  read -rp "Nouvelle description [${cur_desc}] : " new_desc
  new_desc="${new_desc:-$cur_desc}"

  # Targets
  echo ""
  read -rp "Modifier les cibles ? (y/N) : " edit_targets
  local new_targets="$cur_targets"
  if [[ "$edit_targets" =~ ^[Yy]$ ]]; then
    new_targets=$(_pick_targets "$cur_targets")
    log_info "Cibles : $new_targets"
  fi

  # Skills (toujours proposé)
  local new_skills
  new_skills=$(_pick_skills "$cur_skills")
  log_info "Skills : ${new_skills:-aucun}"

  # Valider avant écriture
  echo ""
  echo -e "${BOLD}Récapitulatif des modifications :${RESET}"
  echo "  label       : $new_label"
  echo "  description : $new_desc"
  echo "  targets     : $new_targets"
  echo "  skills      : $new_skills"
  echo ""
  read -rp "Appliquer ? (Y/n) : " confirm
  confirm="${confirm:-Y}"
  [[ "$confirm" =~ ^[Yy]$ ]] || { log_info "Annulé."; exit 0; }

  _update_frontmatter "$file" "$new_skills" "$new_targets" "$new_label" "$new_desc"

  echo ""
  log_success "Agent '$name' mis à jour → agents/${name}.md"
  log_info    "Relancez le déploiement pour appliquer : ./oc.sh deploy all"
}

# ── DISPATCH ─────────────────────────────────────────────────────────────────

SUBCOMMAND="${1:-}"
shift 2>/dev/null || true

case "$SUBCOMMAND" in
  list)   cmd_list ;;
  info)   cmd_info "$@" ;;
  create) cmd_create ;;
  edit)   cmd_edit "$@" ;;
  *)
    echo -e "${BOLD}oc agent — Gestion des agents canoniques${RESET}"
    echo ""
    echo "  list              Lister les agents disponibles"
    echo "  info <agent-id>   Afficher le détail d'un agent"
    echo "  create            Créer un nouvel agent (interactif)"
    echo "  edit <agent-id>   Modifier les skills et métadonnées d'un agent"
    echo ""
    echo -e "${BOLD}Exemples :${RESET}"
    echo "  ./oc.sh agent list"
    echo "  ./oc.sh agent create"
    echo "  ./oc.sh agent edit developer"
    echo "  ./oc.sh agent info planner"
    echo ""
    ;;
esac
